export interface SyllabusTopic {
    id: string; // Deterministic ID: [subj]_[class]_[slug]
    topic: string;
    class: 'Class 8' | 'Class 9' | 'Class 10' | 'Class 11' | 'Class 12';
    weightage: 'High' | 'Medium' | 'Low';
    examPattern: 'Passage' | 'MCQ' | 'Numerical';
    subtopics: string[];
    prerequisites?: string[];
    related_math_ids?: string[]; // Neural link to Math prerequisites
}

export const SYLLABUS_DB: Record<string, SyllabusTopic[]> = {
    Physics: [
        { id: "phy_11_unit_meas", topic: "Units and Measurements", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["SI Units", "Dimensions", "Errors in Measuring Instruments"] },
        { id: "phy_11_motion_line", topic: "Motion in a Straight Line", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Velocity", "Acceleration", "Relative Velocity", "Kinematic Equations"], prerequisites: ["phy_11_unit_meas"], related_math_ids: ["math_11_limits_derivatives"] },
        { id: "phy_11_motion_plane", topic: "Motion in a Plane", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Vectors", "Projectile Motion", "Uniform Circular Motion"], prerequisites: ["phy_11_unit_meas"], related_math_ids: ["math_11_trigonometry"] },
        { id: "phy_11_laws_motion", topic: "Laws of Motion", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Newton's Laws", "Friction", "Circular Motion Dynamics"], prerequisites: ["phy_11_motion_line"] },
        { id: "phy_11_work_energy", topic: "Work, Energy and Power", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Work-Energy Theorem", "Potential Energy", "Collisions"], prerequisites: ["phy_11_laws_motion"], related_math_ids: ["math_12_integrals"] },
        { id: "phy_11_rotational", topic: "Rotational Motion", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Center of Mass", "Torque", "Moment of Inertia", "Rolling Motion"], prerequisites: ["phy_11_laws_motion", "phy_11_motion_plane"], related_math_ids: ["math_12_vector_algebra"] },
        { id: "phy_11_gravitation", topic: "Gravitation", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Kepler's Laws", "Escape Velocity", "Satellites"] },
        { id: "phy_11_solids", topic: "Mechanical Properties of Solids", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Stress", "Strain", "Hooke's Law", "Young's Modulus"] },
        { id: "phy_11_fluids", topic: "Mechanical Properties of Fluids", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Pascal's Law", "Bernoulli's Principle", "Viscosity", "Surface Tension"] },
        { id: "phy_11_thermal", topic: "Thermal Properties of Matter", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Thermal Expansion", "Specific Heat", "Heat Transfer"] },
        { id: "phy_11_thermodynamics", topic: "Thermodynamics", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Laws of Thermodynamics", "Heat Engines", "Specific Heat"] },
        { id: "phy_11_ktg", topic: "Kinetic Theory", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Ideal Gas Equation", "Kinetic Energy", "Specific Heat Capacity"] },
        { id: "phy_11_oscillations", topic: "Oscillations", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["SHM", "Simple Pendulum", "Resonance"], related_math_ids: ["math_11_trigonometry"] },
        { id: "phy_11_waves", topic: "Waves", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Transverse/Longitudinal", "Doppler Effect", "Beats"] },
        { id: "phy_11_physical_world", topic: "Physical World", class: "Class 11", weightage: "Low", examPattern: "MCQ", subtopics: ["Scope of Physics", "Fundamental Forces", "Nature of Laws"] },
        { id: "phy_12_electrostatics", topic: "Electrostatics", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Electric Field", "Flux", "Dipole", "Capacitors"], related_math_ids: ["math_12_vector_algebra", "math_12_integrals"] },
        { id: "phy_12_current", topic: "Current Electricity", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Ohm's Law", "Kirchhoff's Laws", "Potentiometer"] },
        { id: "phy_12_mag_effects", topic: "Magnetic Effects of Current", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Biot-Savart Law", "Ampere's Law", "Moving Coil Galvanometer"], related_math_ids: ["math_12_vector_algebra"] },
        { id: "phy_12_magnetism", topic: "Magnetism and Matter", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Earth's Magnetism", "Magnetic Properties", "Hysteresis"] },
        { id: "phy_12_emi", topic: "Electromagnetic Induction", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Faraday's Law", "Lenz's Law", "Inductance"] },
        { id: "phy_12_ac", topic: "Alternating Current", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["LCR Circuits", "Resonance", "Power Factor", "Transformers"], related_math_ids: ["math_12_integrals"] },
        { id: "phy_12_em_waves", topic: "Electromagnetic Waves", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Spectrum", "Properties", "Applications"] },
        { id: "phy_12_ray_optics", topic: "Ray Optics", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Reflection", "Refraction", "Lenses", "Prisms", "Optical Instruments"], related_math_ids: ["math_11_trigonometry"] },
        { id: "phy_12_wave_optics", topic: "Wave Optics", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Huygens Principle", "Interference", "Diffraction", "Polarization"] },
        { id: "phy_12_dual_nature", topic: "Dual Nature of Radiation", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Photoelectric Effect", "De Broglie Wavelength"] },
        { id: "phy_12_atoms", topic: "Atoms", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Bohr Model", "Hydrogen Spectrum"] },
        { id: "phy_12_nuclei", topic: "Nuclei", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Radioactivity", "Binding Energy", "Fission/Fusion"] },
        { id: "phy_12_semiconductors", topic: "Semiconductor Electronics", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Diodes", "Transistors", "Logic Gates"] },
        { id: "phy_12_communication", topic: "Communication Systems", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Modulation", "Bandwidth", "Propagation"] }
    ],
    Chemistry: [
        { id: "che_11_some_basic_conc", topic: "Some Basic Concepts of Chemistry", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Stoichiometry", "Mole Concept", "Concentration Terms"] },
        { id: "che_11_structure_of_th", topic: "Structure of The Atom", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Bohr Model", "Quantum Numbers", "Electronic Config"], prerequisites: ["che_11_some_basic_conc"] },
        { id: "che_11_classification", topic: "Classification of Elements", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Periodic Trends", "Ionization Enthalpy", "Electronegativity"], prerequisites: ["che_11_structure_of_th"] },
        { id: "che_11_chemical_bondin", topic: "Chemical Bonding", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["VSEPR", "Hybridization", "MOT", "Hydrogen Bonding"], prerequisites: ["che_11_structure_of_th", "che_11_classification"] },
        { id: "che_11_states_of_matte", topic: "States of Matter", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Gas Laws", "Ideal Gas Equation", "Intermolecular Forces"], prerequisites: ["che_11_some_basic_conc"] },
        { id: "che_11_thermodynamics", topic: "Thermodynamics", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Enthalpy", "Entropy", "Gibbs Free Energy"], prerequisites: ["che_11_some_basic_conc", "che_11_states_of_matte"] },
        { id: "che_11_equilibrium", topic: "Equilibrium", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Le Chatelier Principle", "pH Calculation", "Solubility Product"] },
        { id: "che_11_redox_reactions", topic: "Redox Reactions", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Oxidation Number", "Balancing Equations", "Elecrochemical Cells"] },
        { id: "che_11_hydrogen", topic: "Hydrogen", class: "Class 11", weightage: "Low", examPattern: "MCQ", subtopics: ["Preparation", "Hydrides", "Water"] },
        { id: "che_11_the_sblock_elem", topic: "The S-Block Elements", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Alkali Metals", "Alkaline Earth Metals", "Trends"] },
        { id: "che_11_the_pblock_elem", topic: "The P-Block Elements (11)", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Group 13", "Group 14", "Boron Family", "Carbon Family"] },
        { id: "che_11_organic_chemist", topic: "Organic Chemistry: Basic Principles", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["IUPAC", "Isomerism", "GOC", "Reaction Mechanisms"] },
        { id: "che_11_hydrocarbons", topic: "Hydrocarbons", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Alkanes", "Alkenes", "Alkynes", "Aromatic Hydrocarbons"] },
        { id: "che_11_environmental_c", topic: "Environmental Chemistry", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Pollution", "Ozone Depletion", "Green Chemistry"] },
        { id: "che_12_solid_state", topic: "Solid State", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Unit Cells", "Packing Efficiency", "Defects"] },
        { id: "che_12_solutions", topic: "Solutions", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Colligative Properties", "Raoult's Law", "Ideal Solutions"] },
        { id: "che_12_electrochemistr", topic: "Electrochemistry", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Nernst Equation", "Conductance", "Batteries"] },
        { id: "che_12_chemical_kineti", topic: "Chemical Kinetics", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Rate Law", "First Order Reactions", "Arrhenius Equation"] },
        { id: "che_12_surface_chemist", topic: "Surface Chemistry", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Adsorption", "Catalysis", "Colloids"] },
        { id: "che_12_metallurgy", topic: "Metallurgy", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Concentration", "Refining", "Extraction Processes"] },
        { id: "che_12_the_pblock_elem", topic: "The P-Block Elements (12)", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Group 15-18", "Preparation", "Properties"] },
        { id: "che_12_d_and_f_block_e", topic: "D and F Block Elements", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Transition Metals", "Lanthanoids", "Actinoids"] },
        { id: "che_12_coordination_co", topic: "Coordination Compounds", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["IUPAC Naming", "Isomerism", "CFT", "VBT"] },
        { id: "che_12_haloalkanes_and", topic: "Haloalkanes and Haloarenes", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["SN1/SN2", "Preparation", "Reactions"] },
        { id: "che_12_alcohols_phenol", topic: "Alcohols, Phenols and Ethers", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Preparation", "Reactions", "Acidity"] },
        { id: "che_12_aldehydes_keton", topic: "Aldehydes, Ketones and Carboxylic Acids", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Preparation", "Nucleophilic Addition", "Aldol Condensation"] },
        { id: "che_12_amines", topic: "Amines", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Basicity", "Diazonium Salts", "Preparation"] },
        { id: "che_12_biomolecules", topic: "Biomolecules", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Carbohydrates", "Proteins", "Vitamins", "Nucleic Acids"] },
        { id: "che_12_polymers", topic: "Polymers", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Types", "Biodegradable", "Mechanism"] },
        { id: "che_12_chemistry_in_ev", topic: "Chemistry in Everyday Life", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Drugs", "Food Preservatives", "Soaps & Detergents"] }
    ],
    Mathematics: [
        { id: "math_11_sets", topic: "Sets", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Types of Sets", "Venn Diagrams", "Operations"] },
        { id: "math_11_relations_and_f", topic: "Relations and Functions", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Types of Relations", "Domain/Range", "Functions"], prerequisites: ["Sets"] },
        { id: "math_11_trigonometric_f", topic: "Trigonometric Functions", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Identities", "Equations", "Graphs"], prerequisites: ["Relations and Functions"] },
        { id: "math_11_principle_of_ma", topic: "Principle of Mathematical Induction", class: "Class 11", weightage: "Low", examPattern: "MCQ", subtopics: ["Induction Steps", "Applications"] },
        { id: "math_11_complex_numbers", topic: "Complex Numbers", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Modulus", "Argument", "Polar Form", "Roots"] },
        { id: "math_11_linear_inequali", topic: "Linear Inequalities", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Algebraic Solutions", "Graphical Solutions"] },
        { id: "math_11_permutations_an", topic: "Permutations and Combinations", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Factorial", "Arrangements", "Selections"] },
        { id: "math_11_binomial_theore", topic: "Binomial Theorem", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Pascal's Triangle", "General Term", "Expansion"], prerequisites: ["Permutations and Combinations"] },
        { id: "math_11_sequences_and_s", topic: "Sequences and Series", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["AP", "GP", "AM-GM", "Sum of Series"], prerequisites: ["Binomial Theorem", "Linear Inequalities"] },
        { id: "math_11_straight_lines", topic: "Straight Lines", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Slope", "Point-Slope", "Two-Point", "General Eq"] },
        { id: "math_11_conic_sections", topic: "Conic Sections", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Circle", "Parabola", "Ellipse", "Hyperbola"], prerequisites: ["Straight Lines"] },
        { id: "math_11_3d_geometry_int", topic: "3D Geometry (Intro)", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Coordinates", "Distance Formula"] },
        { id: "math_11_limits_and_deri", topic: "Limits and Derivatives", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Standard Limits", "First Principle", "Differentiation"] },
        { id: "math_11_mathematical_re", topic: "Mathematical Reasoning", class: "Class 11", weightage: "Low", examPattern: "MCQ", subtopics: ["Statements", "Logical Operations"] },
        { id: "math_11_statistics", topic: "Statistics", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Mean Deviation", "Variance", "Standard Deviation"] },
        { id: "math_11_probability_int", topic: "Probability (Intro)", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Random Experiments", "Events", "Axiomatic Probability"] },
        { id: "math_12_relations_and_f", topic: "Relations and Functions (12)", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Types", "Binary Operations", "Inverse"] },
        { id: "math_12_inverse_trigono", topic: "Inverse Trigonometric Functions", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Domain/Range", "Properties", "Graphs"] },
        { id: "math_12_matrices", topic: "Matrices", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Types", "Operations", "Transpose", "Invertible"] },
        { id: "math_12_determinants", topic: "Determinants", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Properties", "Area of Triangle", "System of Equations"] },
        { id: "math_12_continuity_and", topic: "Continuity and Differentiability", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Continuity", "Chain Rule", "Mean Value Theorem"] },
        { id: "math_12_app_derivatives", topic: "Application of Derivatives", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Tangent/Normal", "Monotonicity", "Maxima/Minima"] },
        { id: "math_12_integrals", topic: "Integrals", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Indefinite", "Definite Properties", "Area Under Curve"] },
        { id: "math_12_app_integrals", topic: "Application of Integrals", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Area bounded by curves", "Area of circle/ellipse"] },
        { id: "math_12_differential_eq", topic: "Differential Equations", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Order/Degree", "General/Particular Solution", "Linear DE"] },
        { id: "math_12_vector_algebra", topic: "Vector Algebra", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Dot/Cross Product", "Projections", "Direction Cosines"] },
        { id: "math_12_three_dimension", topic: "Three Dimensional Geometry", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Lines", "Planes", "Shortest Distance"] },
        { id: "math_12_linear_programm", topic: "Linear Programming", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Optimization", "Constraints", "Graphical Method"] },
        { id: "math_12_probability", topic: "Probability", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Conditional Probability", "Bayes Theorem", "Distributions"] },
        // Class 10
        { id: "math_10_real_numbers", topic: "Real Numbers", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Euclid's Division", "Fundamental Theorem of Arithmetic"] },
        { id: "math_10_polynomials", topic: "Polynomials", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Zeroes", "Division Algorithm"] },
        { id: "math_10_pair_of_linear", topic: "Pair of Linear Equations", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Substitution", "Elimination", "Cross-Multiplication"] },
        { id: "math_10_quadratic_equat", topic: "Quadratic Equations", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Roots", "Discriminant", "Nature of Roots"] },
        { id: "math_10_arithmetic_prog", topic: "Arithmetic Progressions", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["nth Term", "Sum of n Terms"] },
        { id: "math_10_triangles", topic: "Triangles", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Similarity", "Pythagoras Theorem", "BPT"] },
        { id: "math_10_coordinate_geom", topic: "Coordinate Geometry", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Distance Formula", "Section Formula", "Area of Triangle"] },
        { id: "math_10_introduction_to", topic: "Introduction to Trigonometry", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Ratios", "Identities", "Specific Angles"] },
        { id: "math_10_applications_of", topic: "Applications of Trigonometry", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Heights and Distances"] },
        { id: "math_10_circles", topic: "Circles", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Tangents", "Properties"] },
        { id: "math_10_areas_related_t", topic: "Areas Related to Circles", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Sector", "Segment"] },
        { id: "math_10_surface_areas_a", topic: "Surface Areas and Volumes", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Combination of Solids", "Frustum"] },
        { id: "math_10_statistics", topic: "Statistics", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Mean", "Median", "Mode", "Ogive"] },
        { id: "math_10_probability", topic: "Probability", class: "Class 10", weightage: "Low", examPattern: "Numerical", subtopics: ["Events", "Outcomes"] },
        // Class 9
        { id: "math_9_number_systems", topic: "Number Systems", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Irrational Numbers", "Real Numbers"] },
        { id: "math_9_polynomials", topic: "Polynomials", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Remainder Theorem", "Factor Theorem"] },
        { id: "math_9_linear_equation", topic: "Linear Equations in Two Variables", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Graphing", "Solutions"] },
        { id: "math_9_lines_and_angle", topic: "Lines and Angles", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Pairs of Angles", "Parallel Lines"] },
        { id: "math_9_triangles", topic: "Triangles", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Congruence", "Inequalities"] },
        { id: "math_9_quadrilaterals", topic: "Quadrilaterals", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Types", "Properties", "Mid-point Theorem"] },
        { id: "math_9_circles", topic: "Circles", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Chords", "Arcs", "Cyclic Quadrilaterals"] },
        { id: "math_9_herons_formula", topic: "Heron's Formula", class: "Class 9", weightage: "Low", examPattern: "Numerical", subtopics: ["Area of Triangle"] },
        { id: "math_9_statistics", topic: "Statistics", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Bar Graphs", "Histograms", "Frequency Polygons"] },
        // Class 8
        { id: "math_8_rational_number", topic: "Rational Numbers", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Properties", "Representation"] },
        { id: "math_8_linear_equation", topic: "Linear Equations in One Variable", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Solving Equations", "Applications"] },
        { id: "math_8_understanding_q", topic: "Understanding Quadrilaterals", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Polygons", "Types of Quadrilaterals"] },
        { id: "math_8_data_handling", topic: "Data Handling", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Pie Charts", "Probability"] },
        { id: "math_8_squares_and_squ", topic: "Squares and Square Roots", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Finding Roots", "Properties"] },
        { id: "math_8_cubes_and_cube", topic: "Cubes and Cube Roots", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Finding Cube Roots"] },
        { id: "math_8_comparing_quant", topic: "Comparing Quantities", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Percentage", "Profit/Loss", "Interest"] },
        { id: "math_8_algebraic_expre", topic: "Algebraic Expressions", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Addition/Subtraction", "Identities"] },
        { id: "math_8_mensuration", topic: "Mensuration", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Area", "Volume", "Surface Area"] },
        { id: "math_8_exponents_and_p", topic: "Exponents and Powers", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Laws of Exponents"] },
        { id: "math_8_factorisation", topic: "Factorisation", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Methods", "Division"] },

    ],
    Biology: [
        { id: "bio_11_living_world", topic: "The Living World", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Taxonomy", "Classification Systems"] },
        { id: "bio_11_biological_clas", topic: "Biological Classification", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Monera", "Protista", "Fungi", "Viruses"] },
        { id: "bio_11_plant_kingdom", topic: "Plant Kingdom", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Algae", "Bryophytes", "Pteridophytes", "Gymnosperms"] },
        { id: "bio_11_animal_kingdom", topic: "Animal Kingdom", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Non-Chordates", "Chordates", "Phylums"] },
        { id: "bio_11_morphology_of_f", topic: "Morphology of Flowering Plants", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Roots", "Stems", "Leaves", "Flowers"] },
        { id: "bio_11_anatomy_of_flow", topic: "Anatomy of Flowering Plants", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Tissues", "Internal Structure"] },
        { id: "bio_11_structural_orga", topic: "Structural Organisation in Animals", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Tissues", "Cockroach/Frog/Earthworm"] },
        { id: "bio_11_cell_the_unit_o", topic: "Cell: The Unit of Life", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Cell Structure", "Organelles", "Cell Division"] },
        { id: "bio_11_biomolecules", topic: "Biomolecules", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Enzymes", "Proteins", "Carbohydrates"] },
        { id: "bio_11_cell_cycle_and", topic: "Cell Cycle and Cell Division", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Mitosis", "Meiosis"] },
        { id: "bio_11_transport_in_pl", topic: "Transport in Plants", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Xylem", "Phloem", "Water Potential"] },
        { id: "bio_11_mineral_nutriti", topic: "Mineral Nutrition", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Essential Elements", "Deficiency Symptoms"] },
        { id: "bio_11_photosynthesis", topic: "Photosynthesis in Higher Plants", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Light Reaction", "Dark Reaction", "C3/C4"] },
        { id: "bio_11_respiration_in", topic: "Respiration in Plants", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Glycolysis", "Kreb's Cycle", "ETS"] },
        { id: "bio_11_plant_growth_an", topic: "Plant Growth and Development", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Growth Regulators", "Photoperiodism"] },
        { id: "bio_11_digestion_and_a", topic: "Digestion and Absorption", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Digestive System", "Enzymes", "Disorders"] },
        { id: "bio_11_breathing_and_e", topic: "Breathing and Exchange of Gases", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Respiratory System", "Mechanism", "Transport"] },
        { id: "bio_11_body_fluids_and", topic: "Body Fluids and Circulation", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Blood", "Heart", "ECG", "Disorders"] },
        { id: "bio_11_excretory_produ", topic: "Excretory Products and Elimination", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Kidney", "Nephron", "Urine Formation"] },
        { id: "bio_11_locomotion_and", topic: "Locomotion and Movement", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Muscles", "Skeletal System", "Joints"] },
        { id: "bio_11_neural_control", topic: "Neural Control and Coordination", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Brain", "Nerves", "Eye/Ear"] },
        { id: "bio_11_chemical_coordi", topic: "Chemical Coordination and Integration", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Hormones", "Endocrine Glands"] },
        { id: "bio_12_reproduction_in", topic: "Reproduction in Organisms", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Asexual", "Sexual"] },
        { id: "bio_12_sexual_reproduc", topic: "Sexual Reproduction in Flowering Plants", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Pollination", "Fertilization", "Seed"] },
        { id: "bio_12_human_reproduct", topic: "Human Reproduction", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Reproductive System", "Gametogenesis", "Fertilization"] },
        { id: "bio_12_reproductive_he", topic: "Reproductive Health", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Contraception", "Infertility", "STDs"] },
        { id: "bio_12_principles_of_i", topic: "Principles of Inheritance and Variation", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Mendelism", "Chromosomal Theory", "Genetic Disorders"] },
        { id: "bio_12_molecular_basis", topic: "Molecular Basis of Inheritance", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["DNA", "Replication", "Transcription", "Translation"] },
        { id: "bio_12_evolution", topic: "Evolution", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Origin of Life", "Evidences", "Hardy Weinberg"] },
        { id: "bio_12_human_health_an", topic: "Human Health and Disease", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Immunity", "AIDS", "Cancer", "Drugs"] },
        { id: "bio_12_strategies_for", topic: "Strategies for Enhancement in Food Production", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Animal Husbandry", "Plant Breeding"] },
        { id: "bio_12_microbes_in_hum", topic: "Microbes in Human Welfare", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Household", "Industrial", "Sewage Treatment"] },
        { id: "bio_12_biotechnology_p", topic: "Biotechnology: Principles and Processes", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["rDNA Technology", "Tools"] },
        { id: "bio_12_biotechnology_a", topic: "Biotechnology and its Applications", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Agriculture", "Medicine", "Ethics"] },
        { id: "bio_12_organisms_and_p", topic: "Organisms and Populations", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Adaptations", "Population Growth"] },
        { id: "bio_12_ecosystem", topic: "Ecosystem", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Structure", "Function", "Energy Flow"] },
        { id: "bio_12_biodiversity_an", topic: "Biodiversity and Conservation", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Loss of Biodiversity", "Conservation Methods"] },
        { id: "bio_12_environmental_i", topic: "Environmental Issues", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Pollution", "Ozone Depletion", "Global Warming"] }
    ],

    "Computer Science": [
        { id: "cs_11_ds_linear", topic: "Data Structures: Linear", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Arrays", "Stacks", "Queues", "Linked Lists"] },
        { id: "cs_11_ds_nonlinear", topic: "Data Structures: Non-Linear", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Trees", "BST", "Heaps", "Graphs", "Hashing"] },
        { id: "cs_11_algorithms_anal", topic: "Algorithms: Analysis", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Asymptotic Notation", "Complexity", "Recurrence"] },
        { id: "cs_11_algorithms_desi", topic: "Algorithms: Design", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Divide & Conquer", "Greedy", "Dynamic Programming"] },
        { id: "cs_11_digital_logic", topic: "Digital Logic", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Boolean Algebra", "Combinational Ckts", "Sequential Ckts"] },
        { id: "cs_11_computer_organi", topic: "Computer Organization", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Addressing Modes", "Pipelining", "Cache Memory", "IO"] },
        { id: "cs_12_operating_syste", topic: "Operating Systems", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Processes", "Threads", "CPU Scheduling", "Deadlocks", "Memory Mgmt"] },
        { id: "cs_12_databases_dbms", topic: "Databases (DBMS)", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["ER Model", "SQL", "Normalization", "Transactions", "Indexing"] },
        { id: "cs_12_computer_networ", topic: "Computer Networks", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["OSI/TCP Model", "IP Addressing", "Routing", "Transport Layer", "App Layer"] },
        { id: "cs_12_theory_of_compu", topic: "Theory of Computation", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Regular Languages", "DFA/NFA", "Context Free", "Turing Machines"] },
        { id: "cs_12_compiler_design", topic: "Compiler Design", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Lexical Analysis", "Parsing", "Syntax Directed Translation"] }
    ],
    "Science": [
        // Class 10
        { id: "bio_10_chemical_reacti", topic: "Chemical Reactions and Equations", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Balancing", "Types of Reactions"] },
        { id: "bio_10_acids_bases_and", topic: "Acids, Bases and Salts", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Indicators", "pH Scale", "Salts"] },
        { id: "bio_10_metals_and_nonm", topic: "Metals and Non-Metals", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Properties", "Reactivity Series"] },
        { id: "bio_10_carbon_and_its", topic: "Carbon and its Compounds", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Bonding", "Versatile Nature", "Homologous Series"] },
        { id: "bio_10_periodic_classi", topic: "Periodic Classification of Elements", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Dobereiner", "Newlands", "Mendeleev", "Modern Table"] },
        { id: "bio_10_life_processes", topic: "Life Processes", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Nutrition", "Respiration", "Transportation", "Excretion"] },
        { id: "bio_10_control_and_coo", topic: "Control and Coordination", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Nervous System", "Hormones"] },
        { id: "bio_10_how_do_organism", topic: "How do Organisms Reproduce?", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Asexual", "Sexual", "Reproductive Health"] },
        { id: "bio_10_heredity_and_ev", topic: "Heredity and Evolution", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Mendel's Laws", "Sex Determination", "Evolution"] },
        { id: "bio_10_light_reflectio", topic: "Light – Reflection and Refraction", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Mirrors", "Lenses", "Refractive Index"] },
        { id: "bio_10_human_eye_and_c", topic: "Human Eye and Colourful World", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Defects", "Dispersion", "Scattering"] },
        { id: "bio_10_electricity", topic: "Electricity", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Ohm's Law", "Resistance", "Power", "Heating Effect"] },
        { id: "bio_10_magnetic_effect", topic: "Magnetic Effects of Electric Current", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Field Lines", "Motor", "Generator", "Induction"] },
        { id: "bio_10_sources_of_ener", topic: "Sources of Energy", class: "Class 10", weightage: "Low", examPattern: "MCQ", subtopics: ["Renewable", "Non-renewable"] },
        { id: "bio_10_our_environment", topic: "Our Environment", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Ecosystem", "Ozone Layer"] },
        { id: "bio_10_management_of_n", topic: "Management of Natural Resources", class: "Class 10", weightage: "Low", examPattern: "MCQ", subtopics: ["Conservation", "Dams"] },

        // Class 9
        { id: "bio_9_matter_in_our_s", topic: "Matter in Our Surroundings", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["States of Matter", "Evaporation"] },
        { id: "bio_9_is_matter_aroun", topic: "Is Matter Around Us Pure", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Mixtures", "Solutions", "Separation"] },
        { id: "bio_9_atoms_and_molec", topic: "Atoms and Molecules", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Laws of Chemical Combination", "Mole Concept"] },
        { id: "bio_9_structure_of_th", topic: "Structure of the Atom", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Electrons", "Protons", "Neutrons", "Models"] },
        { id: "bio_9_the_fundamental", topic: "The Fundamental Unit of Life", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Cell Structure", "Organelles"] },
        { id: "bio_9_tissues", topic: "Tissues", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Plant Tissues", "Animal Tissues"] },
        { id: "bio_9_diversity_in_li", topic: "Diversity in Living Organisms", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Classification", "Five Kingdoms"] },
        { id: "bio_9_motion", topic: "Motion", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Distance", "Velocity", "Equations of Motion"] },
        { id: "bio_9_force_and_laws", topic: "Force and Laws of Motion", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Newton's Laws", "Inertia", "Momentum"] },
        { id: "bio_9_gravitation", topic: "Gravitation", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Universal Law", "Free Fall", "Mass vs Weight", "Buoyancy"] },
        { id: "bio_9_work_and_energy", topic: "Work and Energy", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Work", "Energy Types", "Power"] },
        { id: "bio_9_sound", topic: "Sound", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Propagation", "Echo", "Sonar"] },
        { id: "bio_9_why_do_we_fall", topic: "Why Do We Fall Ill", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Health", "Diseases", "Prevention"] },
        { id: "bio_9_natural_resourc", topic: "Natural Resources", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Air", "Water", "Soil", "Biogeochemical Cycles"] },
        { id: "bio_9_improvement_in", topic: "Improvement in Food Resources", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Crop Improvement", "Animal Husbandry"] },

        // Class 8
        { id: "bio_8_crop_production", topic: "Crop Production and Management", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Agricultural Practices"] },
        { id: "bio_8_microorganisms", topic: "Microorganisms: Friend and Foe", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Viruses", "Bacteria", "Preservation"] },
        { id: "bio_8_synthetic_fibre", topic: "Synthetic Fibres and Plastics", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Types", "Characteristics", "Environmental Impact"] },
        { id: "bio_8_materials_metal", topic: "Materials: Metals and Non-Metals", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Physical Properties", "Chemical Properties"] },
        { id: "bio_8_coal_and_petrol", topic: "Coal and Petroleum", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Fossil Fuels", "Formation"] },
        { id: "bio_8_combustion_and", topic: "Combustion and Flame", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Types of Combustion", "Flame Structure", "Fuel Efficiency"] },
        { id: "bio_8_conservation_of", topic: "Conservation of Plants and Animals", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Deforestation", "Biosphere Reserves"] },
        { id: "bio_8_cell_structure", topic: "Cell - Structure and Functions", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Parts of Cell", "Plant vs Animal Cell"] },
        { id: "bio_8_reproduction_in", topic: "Reproduction in Animals", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Modes", "Metamorphosis", "Cloning"] },
        { id: "bio_8_reaching_the_ag", topic: "Reaching the Age of Adolescence", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Puberty", "Hormones", "Reproductive Health"] },
        { id: "bio_8_force_and_press", topic: "Force and Pressure", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Contact/Non-contact Forces", "Pressure"] },
        { id: "bio_8_friction", topic: "Friction", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Causes", "Increasing/Reducing", "Fluid Friction"] },
        { id: "bio_8_sound", topic: "Sound", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Production", "Propagation", "Characteristics", "Noise"] },
        { id: "bio_8_chemical_effect", topic: "Chemical Effects of Electric Current", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Conduction", "Electroplating"] },
        { id: "bio_8_some_natural_ph", topic: "Some Natural Phenomena", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Lightning", "Earthquakes"] },
        { id: "bio_8_light", topic: "Light", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Reflection", "Human Eye", "Care of Eyes"] },
        { id: "bio_8_stars_and_the_s", topic: "Stars and the Solar System", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Moon", "Planets", "Constellations"] },
        { id: "bio_8_pollution_of_ai", topic: "Pollution of Air and Water", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Causes", "Effects", "Prevention"] },


    ],
    "Social Science": [
        // Class 10
        { id: "bio_10_the_rise_of_nat", topic: "The Rise of Nationalism in Europe", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["French Revolution", "Unification"] },
        { id: "bio_10_nationalism_in", topic: "Nationalism in India", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Non-Cooperation", "Civil Disobedience"] },
        { id: "bio_10_the_making_of_a", topic: "The Making of a Global World", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Pre-modern world", "19th Century"] },
        { id: "bio_10_the_age_of_indu", topic: "The Age of Industrialisation", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Factories", "Industrial Growth"] },
        { id: "bio_10_print_culture_a", topic: "Print Culture and the Modern World", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Print Revolution", "Reading Mania"] },
        { id: "bio_10_resources_and_d", topic: "Resources and Development", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Land", "Soil Types"] },
        { id: "bio_10_forest_and_wild", topic: "Forest and Wildlife Resources", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Conservation", "Flora and Fauna"] },
        { id: "bio_10_water_resources", topic: "Water Resources", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Scarcity", "Management"] },
        { id: "bio_10_agriculture", topic: "Agriculture", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Crops", "Farming Types"] },
        { id: "bio_10_minerals_and_en", topic: "Minerals and Energy Resources", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Distribution", "Conservation"] },
        { id: "bio_10_manufacturing_i", topic: "Manufacturing Industries", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Importance", "Classification"] },
        { id: "bio_10_lifelines_of_na", topic: "Lifelines of National Economy", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Transport", "Communication"] },
        { id: "bio_10_power_sharing", topic: "Power Sharing", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Forms", "Belgium/Sri Lanka"] },
        { id: "bio_10_federalism", topic: "Federalism", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Decentralization"] },
        { id: "bio_10_gender_religion", topic: "Gender, Religion and Caste", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Politics", "Social Division"] },
        { id: "bio_10_political_parti", topic: "Political Parties", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Functions", "Challenges"] },
        { id: "bio_10_outcomes_of_dem", topic: "Outcomes of Democracy", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Accountability", "Economic Growth"] },
        { id: "bio_10_development", topic: "Development", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Income", "Public Facilities"] },
        { id: "bio_10_sectors_of_the", topic: "Sectors of the Indian Economy", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Primary/Secondary/Tertiary"] },
        { id: "bio_10_money_and_credi", topic: "Money and Credit", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Banks", "SHGs"] },
        { id: "bio_10_globalisation_a", topic: "Globalisation and the Indian Economy", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["MNCs", "Trade"] },
        { id: "bio_10_consumer_rights", topic: "Consumer Rights", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Exploitation", "Awareness"] },

        // Class 9
        { id: "bio_9_the_french_revo", topic: "The French Revolution", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Causes", "Events", "Impact"] },
        { id: "bio_9_socialism_in_eu", topic: "Socialism in Europe and the Russian Revolution", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Social changes", "Bolsheviks"] },
        { id: "bio_9_nazism_and_the", topic: "Nazism and the Rise of Hitler", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Ideology", "Impact", "Holocaust"] },
        { id: "bio_9_forest_society", topic: "Forest Society and Colonialism", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Deforestation", "Commercial Forestry"] },
        { id: "bio_9_pastoralists_in", topic: "Pastoralists in the Modern World", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Nomadism", "Colonial Rule"] },
        { id: "bio_9_india_size_and", topic: "India - Size and Location", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Coordinates", "Neighbors"] },
        { id: "bio_9_physical_featur", topic: "Physical Features of India", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Himalayas", "Plains", "Plateau"] },
        { id: "bio_9_drainage", topic: "Drainage", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["River Systems", "Lakes"] },
        { id: "bio_9_climate", topic: "Climate", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Monsoon", "Seasons"] },
        { id: "bio_9_natural_vegetat", topic: "Natural Vegetation and Wildlife", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Forests", "Conservation"] },
        { id: "bio_9_population", topic: "Population", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Growth", "Distribution"] },
        { id: "bio_9_what_is_democra", topic: "What is Democracy? Why Democracy?", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Features", "Arguments"] },
        { id: "bio_9_constitutional", topic: "Constitutional Design", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Making of Constitution", "Values"] },
        { id: "bio_9_electoral_polit", topic: "Electoral Politics", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Elections", "Code of Conduct"] },
        { id: "bio_9_working_of_inst", topic: "Working of Institutions", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Parliament", "Executive", "Judiciary"] },
        { id: "bio_9_democratic_righ", topic: "Democratic Rights", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Fundamental Rights"] },
        { id: "bio_9_the_story_of_vi", topic: "The Story of Village Palampur", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Farming", "Non-farm activities"] },
        { id: "bio_9_people_as_resou", topic: "People as Resource", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Health", "Education", "Unemployment"] },
        { id: "bio_9_poverty_as_a_ch", topic: "Poverty as a Challenge", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Poverty Line", "Estimates"] },
        { id: "bio_9_food_security_i", topic: "Food Security in India", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["PDS", "Buffer Stock"] },

        // Class 8
        { id: "bio_8_how_when_and_wh", topic: "How, When and Where", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Dates", "Periodisation"] },
        { id: "bio_8_from_trade_to_t", topic: "From Trade to Territory", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["East India Company", "Battle of Plassey"] },
        { id: "bio_8_ruling_the_coun", topic: "Ruling the Countryside", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Permanent Settlement", "Ryotwari"] },
        { id: "bio_8_tribals_dikus_a", topic: "Tribals, Dikus and the Vision of a Golden Age", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Tribal Lives", "Birsa Munda"] },
        { id: "bio_8_when_people_reb", topic: "When People Rebel", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["1857 Revolt", "Aftermath"] },
        { id: "bio_8_civilising_the", topic: "Civilising the \"Native\", Educating the Nation", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["English Education", "Orientalists"] },
        { id: "bio_8_women_caste_and", topic: "Women, Caste and Reform", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Reform Movements", "Sati", "Widow Remarriage"] },
        { id: "bio_8_the_making_of_t", topic: "The Making of the National Movement", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["1870s-1947", "Gandhian Era"] },
        { id: "bio_8_india_after_ind", topic: "India After Independence", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Partition", "Constitution"] },
        { id: "bio_8_resources", topic: "Resources", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Types", "Conservation"] },
        { id: "bio_8_land_soil_water", topic: "Land, Soil, Water, Natural Vegetation", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Distribution", "Conservation"] },
        { id: "bio_8_mineral_and_pow", topic: "Mineral and Power Resources", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Extraction", "Distribution"] },
        { id: "bio_8_agriculture", topic: "Agriculture", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Farming Systems", "Crops"] },
        { id: "bio_8_industries", topic: "Industries", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Iron and Steel", "Textile"] },
        { id: "bio_8_human_resources", topic: "Human Resources", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Distribution", "Population"] },
        { id: "bio_8_the_indian_cons", topic: "The Indian Constitution", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Key Features", "Fundamental Rights"] },
        { id: "bio_8_understanding_s", topic: "Understanding Secularism", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Indian Secularism"] },
        { id: "bio_8_why_do_we_need", topic: "Why Do We Need a Parliament?", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Role", "Functions"] },
        { id: "bio_8_understanding_l", topic: "Understanding Laws", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Rule of Law", "Unpopular Laws"] },
        { id: "bio_8_judiciary", topic: "Judiciary", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Structure", "Role"] },
        { id: "bio_8_understanding_o", topic: "Understanding Our Criminal Justice System", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Police", "Courts", "Fair Trial"] },
        { id: "bio_8_understanding_m", topic: "Understanding Marginalisation", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Adivasis", "Minorities"] },
        { id: "bio_8_confronting_mar", topic: "Confronting Marginalisation", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Laws", "Rights"] },
        { id: "bio_8_public_faciliti", topic: "Public Facilities", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Water", "Sanitation"] },
        { id: "bio_8_law_and_social", topic: "Law and Social Justice", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Worker Rights", "Bhopal Gas Tragedy"] },


    ],
    "English": [
        // Class 10 - First Flight & Footprints Without Feet
        { id: "bio_10_a_letter_to_god", topic: "A Letter to God", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Lencho's Faith", "Irony"] },
        { id: "bio_10_nelson_mandela", topic: "Nelson Mandela: Long Walk to Freedom", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Apartheid", "Courage", "Freedom"] },
        { id: "bio_10_two_stories_abo", topic: "Two Stories about Flying", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["His First Flight", "Black Aeroplane"] },
        { id: "bio_10_from_the_diary", topic: "From the Diary of Anne Frank", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Kitty", "Hiding", "School Days"] },
        { id: "bio_10_glimpses_of_ind", topic: "Glimpses of India", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["A Baker from Goa", "Coorg", "Tea from Assam"] },
        { id: "bio_10_madam_rides_the", topic: "Madam Rides the Bus", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Valli's Experience", "Observation"] },
        { id: "bio_10_the_sermon_at_b", topic: "The Sermon at Benares", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Kisa Gotami", "Grief and Acceptance"] },
        { id: "bio_10_dust_of_snow", topic: "Dust of Snow", class: "Class 10", weightage: "Low", examPattern: "Passage", subtopics: ["Nature's Healing", "Poem Analysis"] },
        { id: "bio_10_fire_and_ice", topic: "Fire and Ice", class: "Class 10", weightage: "Low", examPattern: "Passage", subtopics: ["Desire and Hatred", "Poem Analysis"] },
        { id: "bio_10_amanda", topic: "Amanda!", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Freedom vs Restraint", "Parenting"] },
        { id: "bio_10_tenses", topic: "Tenses", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Usage", "Error Spotting"] },
        { id: "bio_10_modals", topic: "Modals", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Usage", "Capability", "Permission"] },
        { id: "bio_10_active_and_pass", topic: "Active and Passive Voice", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Conversion", "Tense Rules"] },
        { id: "bio_10_reported_speech", topic: "Reported Speech", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Direct to Indirect", "Imperatives"] },

        // Class 9 - Beehive & Moments
        { id: "bio_9_the_fun_they_ha", topic: "The Fun They Had", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Future Schools", "Telebooks"] },
        { id: "bio_9_the_sound_of_mu", topic: "The Sound of Music", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Evelyn Glennie", "Bismillah Khan"] },
        { id: "bio_9_the_little_girl", topic: "The Little Girl", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Kezia's Bond", "Strict Father"] },
        { id: "bio_9_a_truly_beautif", topic: "A Truly Beautiful Mind", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Albert Einstein", "Genius"] },
        { id: "bio_9_the_road_not_ta", topic: "The Road Not Taken", class: "Class 9", weightage: "Low", examPattern: "Passage", subtopics: ["Choices", "Regret", "Poem Analysis"] },
        { id: "bio_9_wind", topic: "Wind", class: "Class 9", weightage: "Low", examPattern: "Passage", subtopics: ["Challenges", "Metaphor", "Poem Analysis"] },
        { id: "bio_9_determiners", topic: "Determiners", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Usage", "Articles", "Quantifiers"] },
        { id: "bio_9_prepositions", topic: "Prepositions", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Time", "Place", "Motion"] },
        { id: "bio_9_subjectverb_con", topic: "Subject-Verb Concord", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Agreement Rules"] },

        // Class 8 - Honeydew & It So Happened
        { id: "bio_8_the_best_christ", topic: "The Best Christmas Present in the World", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["War and Peace", "Jim and Connie"] },
        { id: "bio_8_the_tsunami", topic: "The Tsunami", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Survival Stories", "Natural Disaster"] },
        { id: "bio_8_glimpses_of_the", topic: "Glimpses of the Past", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Indian History", "Revolt of 1857"] },
        { id: "bio_8_bepin_choudhury", topic: "Bepin Choudhury's Lapse of Memory", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Psychological Trick", "Friendship"] },
        { id: "bio_8_the_summit_with", topic: "The Summit Within", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Mount Everest", "Mental Conquest"] },
        { id: "bio_8_the_ant_and_the", topic: "The Ant and the Cricket", class: "Class 8", weightage: "Low", examPattern: "Passage", subtopics: ["Fable Analysis", "Hard Work"] },
        { id: "bio_8_geography_lesso", topic: "Geography Lesson", class: "Class 8", weightage: "Low", examPattern: "Passage", subtopics: ["Perspective from Above", "Poem Analysis"] },
        { id: "bio_8_nouns_and_prono", topic: "Nouns and Pronouns", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Types", "Usage"] },
        { id: "bio_8_adjectives", topic: "Adjectives", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Degrees of Comparison", "Order"] },
        { id: "bio_8_conjunctions", topic: "Conjunctions", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Coordinating", "Subordinating"] },


    ]
};



export const SOCIAL_LINKS = {
    twitter: {
        id: 'Ayush_thelegend',
        url: 'https://twitter.com/Ayush_thelegend',
        handle: '@Ayush_thelegend',
        creator: '@Ayush_thelegend'
    },
    threads: {
        id: 'mr._.ayush_kr',
        url: 'https://www.threads.net/@mr._.ayush_kr',
        handle: '@mr._.ayush_kr'
    },
    instagram: {
        id: 'mr._.ayush_kr',
        url: 'https://www.instagram.com/mr._.ayush_kr',
        handle: '@mr._.ayush_kr'
    },
    discord: {
        id: 'hbPWvW3djy',
        url: 'https://discord.gg/hbPWvW3djy'
    },
    linkedin: {
        url: 'https://linkedin.com/company/examcompass'
    },
    email: 'contact@examcompass.pages.dev'
};

// Exam → relevant subjects mapping (used by missionService, recommendationService)
export const EXAM_SUBJECT_MAPPING: Record<string, string[]> = {
    'jee-mains': ['Physics', 'Chemistry', 'Mathematics'],
    'jee-advanced': ['Physics', 'Chemistry', 'Mathematics'],
    'neet': ['Physics', 'Chemistry', 'Biology'],
    'class-12': ['Physics', 'Chemistry', 'Mathematics', 'Biology'],
    'class-11': ['Physics', 'Chemistry', 'Mathematics', 'Biology'],
    'class-10': ['Science', 'Mathematics', 'Social Science', 'English'],
    'class-9': ['Science', 'Mathematics', 'Social Science', 'English'],
    'class-8': ['Science', 'Mathematics', 'Social Science', 'English'],
};
