export interface SyllabusTopic {
    topic: string;
    class: 'Class 6' | 'Class 7' | 'Class 8' | 'Class 9' | 'Class 10' | 'Class 11' | 'Class 12';
    weightage: 'High' | 'Medium' | 'Low';
    examPattern: 'Passage' | 'MCQ' | 'Numerical';
    subtopics: string[];
}

export const SYLLABUS_DB: Record<string, SyllabusTopic[]> = {
    Physics: [
        { topic: "Units and Measurements", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["SI Units", "Dimensions", "Errors in Measuring Instruments"] },
        { topic: "Motion in a Straight Line", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Velocity", "Acceleration", "Relative Velocity", "Kinematic Equations"] },
        { topic: "Motion in a Plane", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Vectors", "Projectile Motion", "Uniform Circular Motion"] },
        { topic: "Laws of Motion", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Newton's Laws", "Friction", "Circular Motion Dynamics"] },
        { topic: "Work, Energy and Power", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Work-Energy Theorem", "Potential Energy", "Collisions"] },
        { topic: "Rotational Motion", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Center of Mass", "Torque", "Moment of Inertia", "Rolling Motion"] },
        { topic: "Gravitation", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Kepler's Laws", "Escape Velocity", "Satellites"] },
        { topic: "Mechanical Properties of Solids", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Stress", "Strain", "Hooke's Law", "Young's Modulus"] },
        { topic: "Mechanical Properties of Fluids", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Pascal's Law", "Bernoulli's Principle", "Viscosity", "Surface Tension"] },
        { topic: "Thermal Properties of Matter", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Thermal Expansion", "Specific Heat", "Heat Transfer"] },
        { topic: "Thermodynamics", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Laws of Thermodynamics", "Heat Engines", "Specific Heat"] },
        { topic: "Kinetic Theory", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Ideal Gas Equation", "Kinetic Energy", "Specific Heat Capacity"] },
        { topic: "Oscillations", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["SHM", "Simple Pendulum", "Resonance"] },
        { topic: "Waves", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Transverse/Longitudinal", "Doppler Effect", "Beats"] },
        { topic: "Physical World", class: "Class 11", weightage: "Low", examPattern: "MCQ", subtopics: ["Scope of Physics", "Fundamental Forces", "Nature of Laws"] },
        { topic: "Electrostatics", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Electric Field", "Flux", "Dipole", "Capacitors"] },
        { topic: "Current Electricity", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Ohm's Law", "Kirchhoff's Laws", "Potentiometer"] },
        { topic: "Magnetic Effects of Current", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Biot-Savart Law", "Ampere's Law", "Moving Coil Galvanometer"] },
        { topic: "Magnetism and Matter", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Earth's Magnetism", "Magnetic Properties", "Hysteresis"] },
        { topic: "Electromagnetic Induction", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Faraday's Law", "Lenz's Law", "Inductance"] },
        { topic: "Alternating Current", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["LCR Circuits", "Resonance", "Power Factor", "Transformers"] },
        { topic: "Electromagnetic Waves", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Spectrum", "Properties", "Applications"] },
        { topic: "Ray Optics", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Reflection", "Refraction", "Lenses", "Prisms", "Optical Instruments"] },
        { topic: "Wave Optics", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Huygens Principle", "Interference", "Diffraction", "Polarization"] },
        { topic: "Dual Nature of Radiation", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Photoelectric Effect", "De Broglie Wavelength"] },
        { topic: "Atoms", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Bohr Model", "Hydrogen Spectrum"] },
        { topic: "Nuclei", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Radioactivity", "Binding Energy", "Fission/Fusion"] },
        { topic: "Semiconductor Electronics", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Diodes", "Transistors", "Logic Gates"] },
        { topic: "Communication Systems", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Modulation", "Bandwidth", "Propagation"] }
    ],
    Chemistry: [
        { topic: "Some Basic Concepts of Chemistry", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Stoichiometry", "Mole Concept", "Concentration Terms"] },
        { topic: "Structure of The Atom", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Bohr Model", "Quantum Numbers", "Electronic Config"] },
        { topic: "Classification of Elements", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Periodic Trends", "Ionization Enthalpy", "Electronegativity"] },
        { topic: "Chemical Bonding", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["VSEPR", "Hybridization", "MOT", "Hydrogen Bonding"] },
        { topic: "States of Matter", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Gas Laws", "Ideal Gas Equation", "Intermolecular Forces"] },
        { topic: "Thermodynamics", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Enthalpy", "Entropy", "Gibbs Free Energy"] },
        { topic: "Equilibrium", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Le Chatelier Principle", "pH Calculation", "Solubility Product"] },
        { topic: "Redox Reactions", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Oxidation Number", "Balancing Equations", "Elecrochemical Cells"] },
        { topic: "Hydrogen", class: "Class 11", weightage: "Low", examPattern: "MCQ", subtopics: ["Preparation", "Hydrides", "Water"] },
        { topic: "The S-Block Elements", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Alkali Metals", "Alkaline Earth Metals", "Trends"] },
        { topic: "The P-Block Elements (11)", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Group 13", "Group 14", "Boron Family", "Carbon Family"] },
        { topic: "Organic Chemistry: Basic Principles", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["IUPAC", "Isomerism", "GOC", "Reaction Mechanisms"] },
        { topic: "Hydrocarbons", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Alkanes", "Alkenes", "Alkynes", "Aromatic Hydrocarbons"] },
        { topic: "Environmental Chemistry", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Pollution", "Ozone Depletion", "Green Chemistry"] },
        { topic: "Solid State", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Unit Cells", "Packing Efficiency", "Defects"] },
        { topic: "Solutions", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Colligative Properties", "Raoult's Law", "Ideal Solutions"] },
        { topic: "Electrochemistry", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Nernst Equation", "Conductance", "Batteries"] },
        { topic: "Chemical Kinetics", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Rate Law", "First Order Reactions", "Arrhenius Equation"] },
        { topic: "Surface Chemistry", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Adsorption", "Catalysis", "Colloids"] },
        { topic: "Metallurgy", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Concentration", "Refining", "Extraction Processes"] },
        { topic: "The P-Block Elements (12)", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Group 15-18", "Preparation", "Properties"] },
        { topic: "D and F Block Elements", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Transition Metals", "Lanthanoids", "Actinoids"] },
        { topic: "Coordination Compounds", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["IUPAC Naming", "Isomerism", "CFT", "VBT"] },
        { topic: "Haloalkanes and Haloarenes", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["SN1/SN2", "Preparation", "Reactions"] },
        { topic: "Alcohols, Phenols and Ethers", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Preparation", "Reactions", "Acidity"] },
        { topic: "Aldehydes, Ketones and Carboxylic Acids", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Preparation", "Nucleophilic Addition", "Aldol Condensation"] },
        { topic: "Amines", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Basicity", "Diazonium Salts", "Preparation"] },
        { topic: "Biomolecules", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Carbohydrates", "Proteins", "Vitamins", "Nucleic Acids"] },
        { topic: "Polymers", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Types", "Biodegradable", "Mechanism"] },
        { topic: "Chemistry in Everyday Life", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Drugs", "Food Preservatives", "Soaps & Detergents"] }
    ],
    Mathematics: [
        { topic: "Sets", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Types of Sets", "Venn Diagrams", "Operations"] },
        { topic: "Relations and Functions", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Types of Relations", "Domain/Range", "Functions"] },
        { topic: "Trigonometric Functions", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Identities", "Equations", "Graphs"] },
        { topic: "Principle of Mathematical Induction", class: "Class 11", weightage: "Low", examPattern: "MCQ", subtopics: ["Induction Steps", "Applications"] },
        { topic: "Complex Numbers", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Modulus", "Argument", "Polar Form", "Roots"] },
        { topic: "Linear Inequalities", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Algebraic Solutions", "Graphical Solutions"] },
        { topic: "Permutations and Combinations", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Factorial", "Arrangements", "Selections"] },
        { topic: "Binomial Theorem", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Pascal's Triangle", "General Term", "Expansion"] },
        { topic: "Sequences and Series", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["AP", "GP", "AM-GM", "Sum of Series"] },
        { topic: "Straight Lines", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Slope", "Point-Slope", "Two-Point", "General Eq"] },
        { topic: "Conic Sections", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Circle", "Parabola", "Ellipse", "Hyperbola"] },
        { topic: "3D Geometry (Intro)", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Coordinates", "Distance Formula"] },
        { topic: "Limits and Derivatives", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Standard Limits", "First Principle", "Differentiation"] },
        { topic: "Mathematical Reasoning", class: "Class 11", weightage: "Low", examPattern: "MCQ", subtopics: ["Statements", "Logical Operations"] },
        { topic: "Statistics", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Mean Deviation", "Variance", "Standard Deviation"] },
        { topic: "Probability (Intro)", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Random Experiments", "Events", "Axiomatic Probability"] },
        { topic: "Relations and Functions (12)", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Types", "Binary Operations", "Inverse"] },
        { topic: "Inverse Trigonometric Functions", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Domain/Range", "Properties", "Graphs"] },
        { topic: "Matrices", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Types", "Operations", "Transpose", "Invertible"] },
        { topic: "Determinants", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Properties", "Area of Triangle", "System of Equations"] },
        { topic: "Continuity and Differentiability", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Continuity", "Chain Rule", "Mean Value Theorem"] },
        { topic: "Application of Derivatives", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Tangent/Normal", "Monotonicity", "Maxima/Minima"] },
        { topic: "Integrals", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Indefinite", "Definite Properties", "Area Under Curve"] },
        { topic: "Application of Integrals", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Area bounded by curves", "Area of circle/ellipse"] },
        { topic: "Differential Equations", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Order/Degree", "General/Particular Solution", "Linear DE"] },
        { topic: "Vector Algebra", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Dot/Cross Product", "Projections", "Direction Cosines"] },
        { topic: "Three Dimensional Geometry", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Lines", "Planes", "Shortest Distance"] },
        { topic: "Linear Programming", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Optimization", "Constraints", "Graphical Method"] },
        { topic: "Probability", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Conditional Probability", "Bayes Theorem", "Distributions"] },
        // Class 10
        { topic: "Real Numbers", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Euclid's Division", "Fundamental Theorem of Arithmetic"] },
        { topic: "Polynomials", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Zeroes", "Division Algorithm"] },
        { topic: "Pair of Linear Equations", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Substitution", "Elimination", "Cross-Multiplication"] },
        { topic: "Quadratic Equations", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Roots", "Discriminant", "Nature of Roots"] },
        { topic: "Arithmetic Progressions", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["nth Term", "Sum of n Terms"] },
        { topic: "Triangles", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Similarity", "Pythagoras Theorem", "BPT"] },
        { topic: "Coordinate Geometry", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Distance Formula", "Section Formula", "Area of Triangle"] },
        { topic: "Introduction to Trigonometry", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Ratios", "Identities", "Specific Angles"] },
        { topic: "Applications of Trigonometry", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Heights and Distances"] },
        { topic: "Circles", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Tangents", "Properties"] },
        { topic: "Areas Related to Circles", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Sector", "Segment"] },
        { topic: "Surface Areas and Volumes", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Combination of Solids", "Frustum"] },
        { topic: "Statistics", class: "Class 10", weightage: "Medium", examPattern: "Numerical", subtopics: ["Mean", "Median", "Mode", "Ogive"] },
        { topic: "Probability", class: "Class 10", weightage: "Low", examPattern: "Numerical", subtopics: ["Events", "Outcomes"] },
        // Class 9
        { topic: "Number Systems", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Irrational Numbers", "Real Numbers"] },
        { topic: "Polynomials", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Remainder Theorem", "Factor Theorem"] },
        { topic: "Linear Equations in Two Variables", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Graphing", "Solutions"] },
        { topic: "Lines and Angles", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Pairs of Angles", "Parallel Lines"] },
        { topic: "Triangles", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Congruence", "Inequalities"] },
        { topic: "Quadrilaterals", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Types", "Properties", "Mid-point Theorem"] },
        { topic: "Circles", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Chords", "Arcs", "Cyclic Quadrilaterals"] },
        { topic: "Heron's Formula", class: "Class 9", weightage: "Low", examPattern: "Numerical", subtopics: ["Area of Triangle"] },
        { topic: "Statistics", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Bar Graphs", "Histograms", "Frequency Polygons"] },
        // Class 8
        { topic: "Rational Numbers", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Properties", "Representation"] },
        { topic: "Linear Equations in One Variable", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Solving Equations", "Applications"] },
        { topic: "Understanding Quadrilaterals", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Polygons", "Types of Quadrilaterals"] },
        { topic: "Data Handling", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Pie Charts", "Probability"] },
        { topic: "Squares and Square Roots", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Finding Roots", "Properties"] },
        { topic: "Cubes and Cube Roots", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Finding Cube Roots"] },
        { topic: "Comparing Quantities", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Percentage", "Profit/Loss", "Interest"] },
        { topic: "Algebraic Expressions", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Addition/Subtraction", "Identities"] },
        { topic: "Mensuration", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Area", "Volume", "Surface Area"] },
        { topic: "Exponents and Powers", class: "Class 8", weightage: "Medium", examPattern: "Numerical", subtopics: ["Laws of Exponents"] },
        { topic: "Factorisation", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Methods", "Division"] },
        // Class 7
        { topic: "Integers", class: "Class 7", weightage: "Medium", examPattern: "Numerical", subtopics: ["Properties", "Operations"] },
        { topic: "Fractions and Decimals", class: "Class 7", weightage: "High", examPattern: "Numerical", subtopics: ["Multiplication", "Division"] },
        { topic: "Data Handling", class: "Class 7", weightage: "Medium", examPattern: "Numerical", subtopics: ["Mean", "Median", "Mode"] },
        { topic: "Simple Equations", class: "Class 7", weightage: "High", examPattern: "Numerical", subtopics: ["Solving", "Word Problems"] },
        { topic: "Lines and Angles", class: "Class 7", weightage: "Medium", examPattern: "Numerical", subtopics: ["Complementary", "Supplementary"] },
        { topic: "The Triangle and its Properties", class: "Class 7", weightage: "High", examPattern: "Numerical", subtopics: ["Medians", "Altitudes", "Exterior Angle"] },
        { topic: "Congruence of Triangles", class: "Class 7", weightage: "High", examPattern: "Numerical", subtopics: ["Criteria (SSS, SAS, ASA, RHS)"] },
        { topic: "Comparing Quantities", class: "Class 7", weightage: "Medium", examPattern: "Numerical", subtopics: ["Ratios", "Percentage"] },
        { topic: "Rational Numbers", class: "Class 7", weightage: "Medium", examPattern: "Numerical", subtopics: ["Operations", "Number Line"] },
        { topic: "Perimeter and Area", class: "Class 7", weightage: "High", examPattern: "Numerical", subtopics: ["Square", "Rectangle", "Circle"] },
        { topic: "Algebraic Expressions", class: "Class 7", weightage: "Medium", examPattern: "Numerical", subtopics: ["Terms", "Factors", "Coefficients"] },
        // Class 6
        { topic: "Knowing Our Numbers", class: "Class 6", weightage: "High", examPattern: "Numerical", subtopics: ["Large Numbers", "Estimation"] },
        { topic: "Whole Numbers", class: "Class 6", weightage: "Medium", examPattern: "Numerical", subtopics: ["Properties", "patterns"] },
        { topic: "Playing with Numbers", class: "Class 6", weightage: "High", examPattern: "Numerical", subtopics: ["Factors", "Multiples", "HCF/LCM"] },
        { topic: "Basic Geometrical Ideas", class: "Class 6", weightage: "Medium", examPattern: "Numerical", subtopics: ["Points", "Lines", "Curves"] },
        { topic: "Integers", class: "Class 6", weightage: "Medium", examPattern: "Numerical", subtopics: ["Number Line", "Addition/Subtraction"] },
        { topic: "Fractions", class: "Class 6", weightage: "High", examPattern: "Numerical", subtopics: ["Types", "Operations"] },
        { topic: "Decimals", class: "Class 6", weightage: "Medium", examPattern: "Numerical", subtopics: ["Place Value", "Operations"] },
        { topic: "Data Handling", class: "Class 6", weightage: "Medium", examPattern: "Numerical", subtopics: ["Recording", "Organization", "Pictograph"] },
        { topic: "Mensuration", class: "Class 6", weightage: "High", examPattern: "Numerical", subtopics: ["Perimeter", "Area"] },
        { topic: "Algebra", class: "Class 6", weightage: "Medium", examPattern: "Numerical", subtopics: ["Variables", "Expressions"] },
        { topic: "Ratio and Proportion", class: "Class 6", weightage: "High", examPattern: "Numerical", subtopics: ["Unitary Method"] }
    ],
    Biology: [
        { topic: "The Living World", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Taxonomy", "Classification Systems"] },
        { topic: "Biological Classification", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Monera", "Protista", "Fungi", "Viruses"] },
        { topic: "Plant Kingdom", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Algae", "Bryophytes", "Pteridophytes", "Gymnosperms"] },
        { topic: "Animal Kingdom", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Non-Chordates", "Chordates", "Phylums"] },
        { topic: "Morphology of Flowering Plants", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Roots", "Stems", "Leaves", "Flowers"] },
        { topic: "Anatomy of Flowering Plants", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Tissues", "Internal Structure"] },
        { topic: "Structural Organisation in Animals", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Tissues", "Cockroach/Frog/Earthworm"] },
        { topic: "Cell: The Unit of Life", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Cell Structure", "Organelles", "Cell Division"] },
        { topic: "Biomolecules", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Enzymes", "Proteins", "Carbohydrates"] },
        { topic: "Cell Cycle and Cell Division", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Mitosis", "Meiosis"] },
        { topic: "Transport in Plants", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Xylem", "Phloem", "Water Potential"] },
        { topic: "Mineral Nutrition", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Essential Elements", "Deficiency Symptoms"] },
        { topic: "Photosynthesis in Higher Plants", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Light Reaction", "Dark Reaction", "C3/C4"] },
        { topic: "Respiration in Plants", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Glycolysis", "Kreb's Cycle", "ETS"] },
        { topic: "Plant Growth and Development", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Growth Regulators", "Photoperiodism"] },
        { topic: "Digestion and Absorption", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Digestive System", "Enzymes", "Disorders"] },
        { topic: "Breathing and Exchange of Gases", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Respiratory System", "Mechanism", "Transport"] },
        { topic: "Body Fluids and Circulation", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Blood", "Heart", "ECG", "Disorders"] },
        { topic: "Excretory Products and Elimination", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Kidney", "Nephron", "Urine Formation"] },
        { topic: "Locomotion and Movement", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Muscles", "Skeletal System", "Joints"] },
        { topic: "Neural Control and Coordination", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Brain", "Nerves", "Eye/Ear"] },
        { topic: "Chemical Coordination and Integration", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Hormones", "Endocrine Glands"] },
        { topic: "Reproduction in Organisms", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Asexual", "Sexual"] },
        { topic: "Sexual Reproduction in Flowering Plants", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Pollination", "Fertilization", "Seed"] },
        { topic: "Human Reproduction", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Reproductive System", "Gametogenesis", "Fertilization"] },
        { topic: "Reproductive Health", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Contraception", "Infertility", "STDs"] },
        { topic: "Principles of Inheritance and Variation", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Mendelism", "Chromosomal Theory", "Genetic Disorders"] },
        { topic: "Molecular Basis of Inheritance", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["DNA", "Replication", "Transcription", "Translation"] },
        { topic: "Evolution", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Origin of Life", "Evidences", "Hardy Weinberg"] },
        { topic: "Human Health and Disease", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Immunity", "AIDS", "Cancer", "Drugs"] },
        { topic: "Strategies for Enhancement in Food Production", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Animal Husbandry", "Plant Breeding"] },
        { topic: "Microbes in Human Welfare", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Household", "Industrial", "Sewage Treatment"] },
        { topic: "Biotechnology: Principles and Processes", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["rDNA Technology", "Tools"] },
        { topic: "Biotechnology and its Applications", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Agriculture", "Medicine", "Ethics"] },
        { topic: "Organisms and Populations", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Adaptations", "Population Growth"] },
        { topic: "Ecosystem", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Structure", "Function", "Energy Flow"] },
        { topic: "Biodiversity and Conservation", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Loss of Biodiversity", "Conservation Methods"] },
        { topic: "Environmental Issues", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Pollution", "Ozone Depletion", "Global Warming"] }
    ],
    "History": [
        { topic: "Ancient India: Indus Valley", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Town Planning", "Society", "Decline"] },
        { topic: "Ancient India: Vedic Age", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Rig Vedic", "Later Vedic", "Literature"] },
        { topic: "Ancient India: Mahajanapadas", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["16 Mahajanapadas", "Magadha", "Maurya Rise"] },
        { topic: "Art & Culture: Architecture", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Temple Arch", "Cave Arch", "Mughal Arch"] },
        { topic: "Medieval India: Delhi Sultanate", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Slave Dynasty", "Khiljis", "Tughlaqs"] },
        { topic: "Medieval India: Mughals", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Akbar", "Aurangzeb", "Administration"] },
        { topic: "Medieval India: Bhakti & Sufi", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["Saints", "Philosophy", "Impact"] },
        { topic: "Modern History: 1857 Revolt", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["Causes", "Impact", "Failure"] },
        { topic: "Modern History: Gandhian Era", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["Non-Cooperation", "Civil Disobedience", "Quit India"] },
        { topic: "Modern History: Social Reformers", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Raja Ram Mohan Roy", "Ishwar Chandra Vidyasagar"] },
        { topic: "Modern History: Freedom Struggle", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["Congress Formation", "Extremists/Moderates"] },
        { topic: "World History: Industrial Revolution", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["Causes", "Impact", "Spread"] },
        { topic: "World History: World Wars", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["WW1", "WW2", "Treaty of Versailles"] },
        { topic: "World History: Cold War", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["US vs USSR", "Proxy Wars", "Collapse"] }
    ],
    "Geography": [
        { topic: "Geomorphology", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Earth Interior", "Plate Tectonics", "Earthquakes", "Volcanoes"] },
        { topic: "Climatology", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Atmosphere", "Insolation", "Cyclones", "Climate Zones"] },
        { topic: "Oceanography", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Ocean Floors", "Salinity", "Tides", "Currents"] },
        { topic: "Biogeography", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["Soils", "Vegetation", "Ecosystems"] },
        { topic: "Indian Geography: Physical", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Himalayas", "Peninsula", "Plains", "Drainage"] },
        { topic: "Indian Geography: Climate", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Monsoon", "Seasons", "Rainfall Distribution"] },
        { topic: "Indian Geography: Resources", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Minerals", "Energy", "Water"] },
        { topic: "Indian Geography: Agriculture", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Crops", "Irrigation", "Green Revolution"] },
        { topic: "Human Geography: Population", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Distribution", "Density", "Migration"] },
        { topic: "Human Geography: Settlements", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Rural", "Urban", "Urbanization"] },
        { topic: "Economic Geography", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Industries", "Transport", "Trade"] }
    ],
    "Polity": [
        { topic: "Constitutional Framework", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Preamble", "Salient Features", "Amendments"] },
        { topic: "Fundamental Rights", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Articles 12-35", "Writs", "Exceptions"] },
        { topic: "DPSP & Duties", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Principles", "Fundamental Duties"] },
        { topic: "Parliament", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Lok Sabha", "Rajya Sabha", "Bills", "Committees"] },
        { topic: "Executive", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["President", "Vice-President", "PM", "Council of Ministers"] },
        { topic: "Judiciary", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["Supreme Court", "High Court", "Judicial Review"] },
        { topic: "Federalism", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["Centre-State Relations", "Emergency Provisions"] },
        { topic: "Local Government", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["Panchayati Raj", "Municipalities", "73rd/74th Amendment"] },
        { topic: "Constitutional Bodies", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["ECI", "UPSC", "CAG", "Finance Commission"] }
    ],
    "Economy": [
        { topic: "National Income", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["GDP", "GNP", "NNP", "Methods of Calculation"] },
        { topic: "Inflation", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["Types", "Causes", "Indices (WPI/CPI)", "Control"] },
        { topic: "Monetary Policy", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["RBI", "Repo Rate", "CRR/SLR", "Tools"] },
        { topic: "Fiscal Policy", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["Budget", "Deficits", "Taxation", "GST"] },
        { topic: "Banking System", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Commercial Banks", "NPA", "Basel Norms", "Financial Inclusion"] },
        { topic: "External Sector", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["BoP", "Forex", "FDI/FII", "Convertibility"] },
        { topic: "International Orgs", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["IMF", "World Bank", "WTO", "Trade Agreements"] },
        { topic: "Planning in India", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["Five Year Plans", "NITI Aayog", "Reforms 1991"] },
        { topic: "Agriculture", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["MSP", "Subsidies", "Food Security", "Issues"] },
        { topic: "Poverty & Unemployment", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["Measurement", "Schemes", "Types"] }
    ],
    "General Science": [
        { topic: "Physics: Mechanics", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Motion", "Force", "Gravity", "Pressure"] },
        { topic: "Physics: Heat & Light", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Optics", "Sound", "Thermodynamics basics"] },
        { topic: "Physics: Electricity", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Current", "Magnetism", "Electronics"] },
        { topic: "Chemistry: Substance", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Elements", "Compounds", "Mixtures", "Acids/Bases"] },
        { topic: "Chemistry: Carbon", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Allotropes", "Hydrocarbons", "Polymers"] },
        { topic: "Biology: Cell", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Structure", "Division", "Genetics"] },
        { topic: "Biology: Human Body", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Systems", "Organs", "Functions"] },
        { topic: "Biology: Diseases", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Viral", "Bacterial", "Vaccines"] },
        { topic: "Environment: Ecology", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Ecosystem", "Food Chain", "Biodiversity"] },
        { topic: "Environment: Issues", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Climate Change", "Pollution", "Conservation"] }
    ],
    "English Proficiency": [
        { topic: "Grammar: Tenses", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Past", "Present", "Future", "Conditionals"] },
        { topic: "Grammar: Prepositions", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Time", "Place", "Direction", "Usage"] },
        { topic: "Grammar: Modals", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Can", "Could", "Should", "Would"] },
        { topic: "Grammar: Voice & Speech", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Active/Passive", "Direct/Indirect"] },
        { topic: "Vocabulary: Synonyms & Antonyms", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Contextual usage", "Root words"] },
        { topic: "Vocabulary: Idioms & Phrases", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Common idioms", "Phrasal verbs"] },
        { topic: "Vocabulary: One Word Substitution", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Descriptive terms", "Professional terms"] },
        { topic: "Reading Comprehension", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["Main Idea", "Inference", "Tone", "Vocab in Context"] },
        { topic: "Composition: Rearrangement", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["ParaJumbles", "Sentence Order"] },
        { topic: "Composition: Error Detection", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Spotting Errors", "Sentence Improvement"] },
        { topic: "Composition: Analogies", class: "Class 12", weightage: "Low", examPattern: "MCQ", subtopics: ["Relationship identification", "Word pairs"] }
    ],
    "Logical Reasoning": [
        { topic: "Verbal: Series Completion", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Number Series", "Alphabet Series", "Mixed Series"] },
        { topic: "Verbal: Analogy", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Word Analogy", "Number Analogy"] },
        { topic: "Verbal: Classification", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Odd one out", "Group selection"] },
        { topic: "Verbal: Coding-Decoding", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Letter Coding", "Substitution", "Pattern"] },
        { topic: "Verbal: Blood Relations", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Family Tree", "Coded Relations"] },
        { topic: "Verbal: Direction Sense", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Angles", "Distance", "Shadows"] },
        { topic: "Non-Verbal: Pattern Completion", class: "Class 11", weightage: "High", examPattern: "MCQ", subtopics: ["Figure Matrix", "Shape Construction"] },
        { topic: "Non-Verbal: Paper Cutting", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Folding", "Punching"] },
        { topic: "Non-Verbal: Figure Series", class: "Class 11", weightage: "Medium", examPattern: "MCQ", subtopics: ["Next figure", "Missing figure"] },
        { topic: "Critical: Arguments", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Strong/Weak arguments", "Forcefulness"] },
        { topic: "Critical: Assumptions", class: "Class 12", weightage: "High", examPattern: "MCQ", subtopics: ["Implicit assumptions", "Validity"] },
        { topic: "Critical: Course of Action", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Problem solving", "Decision making"] },
        { topic: "Critical: Syllogism", class: "Class 12", weightage: "Medium", examPattern: "MCQ", subtopics: ["Venn Diagrams", "Conclusions"] }
    ],
    "Legal Reasoning": [
        { topic: "Law of Torts", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Negligence", "Defamation", "Nuisance", "Strict Liability", "Vicarious Liability"] },
        { topic: "Law of Contracts", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Offer & Acceptance", "Consideration", "Breach", "Damages", "Void Agreements"] },
        { topic: "Criminal Law", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["IPC Basics", "Elements of Crime (Mens Rea)", "Theft/Robbery", "Self Defense", "Murder vs Culpable Homicide"] },
        { topic: "Constitutional Law", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["Fundamental Rights", "Writs", "Directive Principles", "Emergency", "Amendment Process"] },
        { topic: "Family Law", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Marriage", "Divorce", "Maintenance", "Succession"] },
        { topic: "International Law", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["UN Bodies", "Treaties", "Human Rights", "ICJ"] },
        { topic: "IPR Basics", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Copyright", "Patents", "Trademarks"] },
        { topic: "Important Legal Maxims", class: "Class 11", weightage: "Medium", examPattern: "Passage", subtopics: ["Latin Terms", "Terminology", "Usage"] },
        { topic: "Miscellaneous Laws", class: "Class 12", weightage: "Low", examPattern: "Passage", subtopics: ["Consumer Protection", "Motor Vehicles", "IT Act"] }
    ],
    "Current Affairs": [
        { topic: "National Events", class: "Class 11", weightage: "High", examPattern: "Passage", subtopics: ["Govt Schemes", "Elections", "Bills & Acts", "Awards"] },
        { topic: "International Events", class: "Class 12", weightage: "High", examPattern: "Passage", subtopics: ["Summits (G20, G7)", "Conflicts", "Appointments", "Treaties"] },
        { topic: "LegalGK Impact", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Supreme Court Judgments", "Legal Appointments", "Commissions"] },
        { topic: "Economics & Business", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Budget", "Economic Survey", "Mergers", "Indices"] },
        { topic: "Science & Tech", class: "Class 12", weightage: "Medium", examPattern: "Passage", subtopics: ["Space Missions", "Defence Tech", "Discoveries"] },
        { topic: "Sports", class: "Class 11", weightage: "Low", examPattern: "Passage", subtopics: ["Tournaments", "Records", "Awards"] },
        { topic: "Books & Authors", class: "Class 11", weightage: "Low", examPattern: "Passage", subtopics: ["New Releases", "Prizes"] }
    ],
    "Quantitative Techniques": [
        { topic: "Percentage", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Basics", "Growth/Decay", "Population"] },
        { topic: "Profit & Loss", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Discounts", "Markup", "False Weights"] },
        { topic: "Simple & Compound Interest", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Formulas", "Installments"] },
        { topic: "Ratio & Proportion", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Partnership", "Mixtures", "Ages"] },
        { topic: "Averages", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Weighted Average", "Properties"] },
        { topic: "Time & Work", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Efficiency", "Pipes & Cisterns"] },
        { topic: "Time, Speed & Distance", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Trains", "Boats & Streams", "Relative Speed"] },
        { topic: "Mensuration", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Area (2D)", "Volume (3D)", "Surface Area"] },
        { topic: "Data Interpretation", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Bar Graphs", "Pie Charts", "Line Graphs", "Tables", "Caselets"] },
        { topic: "Probability", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Basics", "Cards/Dice/Coins"] }
    ],
    "Engineering Mathematics": [
        { topic: "Discrete Mathematics: Sets & Logic", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Propositional Logic", "Predicates", "Sets", "Relations"] },
        { topic: "Discrete Mathematics: Graph Theory", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Connectivity", "Matching", "Coloring", "Path"] },
        { topic: "Discrete Mathematics: Combinatorics", class: "Class 11", weightage: "Medium", examPattern: "Numerical", subtopics: ["Counting", "Recurrence", "Generating Functions"] },
        { topic: "Linear Algebra", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Matrices", "Determinants", "Eigenvalues", "LU Decomposition"] },
        { topic: "Calculus", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Limits", "Continuity", "Differentiation", "Integration", "Max/Min"] },
        { topic: "Probability", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Random Variables", "Distributions", "Statistics", "Bayes"] }
    ],
    "Computer Science": [
        { topic: "Data Structures: Linear", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Arrays", "Stacks", "Queues", "Linked Lists"] },
        { topic: "Data Structures: Non-Linear", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Trees", "BST", "Heaps", "Graphs", "Hashing"] },
        { topic: "Algorithms: Analysis", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Asymptotic Notation", "Complexity", "Recurrence"] },
        { topic: "Algorithms: Design", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Divide & Conquer", "Greedy", "Dynamic Programming"] },
        { topic: "Digital Logic", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Boolean Algebra", "Combinational Ckts", "Sequential Ckts"] },
        { topic: "Computer Organization", class: "Class 11", weightage: "High", examPattern: "Numerical", subtopics: ["Addressing Modes", "Pipelining", "Cache Memory", "IO"] },
        { topic: "Operating Systems", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["Processes", "Threads", "CPU Scheduling", "Deadlocks", "Memory Mgmt"] },
        { topic: "Databases (DBMS)", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["ER Model", "SQL", "Normalization", "Transactions", "Indexing"] },
        { topic: "Computer Networks", class: "Class 12", weightage: "High", examPattern: "Numerical", subtopics: ["OSI/TCP Model", "IP Addressing", "Routing", "Transport Layer", "App Layer"] },
        { topic: "Theory of Computation", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Regular Languages", "DFA/NFA", "Context Free", "Turing Machines"] },
        { topic: "Compiler Design", class: "Class 12", weightage: "Medium", examPattern: "Numerical", subtopics: ["Lexical Analysis", "Parsing", "Syntax Directed Translation"] }
    ],
    "Science": [
        // Class 10
        { topic: "Chemical Reactions and Equations", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Balancing", "Types of Reactions"] },
        { topic: "Acids, Bases and Salts", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Indicators", "pH Scale", "Salts"] },
        { topic: "Metals and Non-Metals", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Properties", "Reactivity Series"] },
        { topic: "Carbon and its Compounds", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Bonding", "Versatile Nature", "Homologous Series"] },
        { topic: "Periodic Classification of Elements", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Dobereiner", "Newlands", "Mendeleev", "Modern Table"] },
        { topic: "Life Processes", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Nutrition", "Respiration", "Transportation", "Excretion"] },
        { topic: "Control and Coordination", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Nervous System", "Hormones"] },
        { topic: "How do Organisms Reproduce?", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Asexual", "Sexual", "Reproductive Health"] },
        { topic: "Heredity and Evolution", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Mendel's Laws", "Sex Determination", "Evolution"] },
        { topic: "Light – Reflection and Refraction", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Mirrors", "Lenses", "Refractive Index"] },
        { topic: "Human Eye and Colourful World", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Defects", "Dispersion", "Scattering"] },
        { topic: "Electricity", class: "Class 10", weightage: "High", examPattern: "Numerical", subtopics: ["Ohm's Law", "Resistance", "Power", "Heating Effect"] },
        { topic: "Magnetic Effects of Electric Current", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Field Lines", "Motor", "Generator", "Induction"] },
        { topic: "Sources of Energy", class: "Class 10", weightage: "Low", examPattern: "MCQ", subtopics: ["Renewable", "Non-renewable"] },
        { topic: "Our Environment", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Ecosystem", "Ozone Layer"] },
        { topic: "Management of Natural Resources", class: "Class 10", weightage: "Low", examPattern: "MCQ", subtopics: ["Conservation", "Dams"] },

        // Class 9
        { topic: "Matter in Our Surroundings", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["States of Matter", "Evaporation"] },
        { topic: "Is Matter Around Us Pure", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Mixtures", "Solutions", "Separation"] },
        { topic: "Atoms and Molecules", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Laws of Chemical Combination", "Mole Concept"] },
        { topic: "Structure of the Atom", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Electrons", "Protons", "Neutrons", "Models"] },
        { topic: "The Fundamental Unit of Life", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Cell Structure", "Organelles"] },
        { topic: "Tissues", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Plant Tissues", "Animal Tissues"] },
        { topic: "Diversity in Living Organisms", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Classification", "Five Kingdoms"] },
        { topic: "Motion", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Distance", "Velocity", "Equations of Motion"] },
        { topic: "Force and Laws of Motion", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Newton's Laws", "Inertia", "Momentum"] },
        { topic: "Gravitation", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Universal Law", "Free Fall", "Mass vs Weight", "Buoyancy"] },
        { topic: "Work and Energy", class: "Class 9", weightage: "High", examPattern: "Numerical", subtopics: ["Work", "Energy Types", "Power"] },
        { topic: "Sound", class: "Class 9", weightage: "Medium", examPattern: "Numerical", subtopics: ["Propagation", "Echo", "Sonar"] },
        { topic: "Why Do We Fall Ill", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Health", "Diseases", "Prevention"] },
        { topic: "Natural Resources", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Air", "Water", "Soil", "Biogeochemical Cycles"] },
        { topic: "Improvement in Food Resources", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Crop Improvement", "Animal Husbandry"] },

        // Class 8
        { topic: "Crop Production and Management", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Agricultural Practices"] },
        { topic: "Microorganisms: Friend and Foe", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Viruses", "Bacteria", "Preservation"] },
        { topic: "Synthetic Fibres and Plastics", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Types", "Characteristics", "Environmental Impact"] },
        { topic: "Materials: Metals and Non-Metals", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Physical Properties", "Chemical Properties"] },
        { topic: "Coal and Petroleum", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Fossil Fuels", "Formation"] },
        { topic: "Combustion and Flame", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Types of Combustion", "Flame Structure", "Fuel Efficiency"] },
        { topic: "Conservation of Plants and Animals", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Deforestation", "Biosphere Reserves"] },
        { topic: "Cell - Structure and Functions", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Parts of Cell", "Plant vs Animal Cell"] },
        { topic: "Reproduction in Animals", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Modes", "Metamorphosis", "Cloning"] },
        { topic: "Reaching the Age of Adolescence", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Puberty", "Hormones", "Reproductive Health"] },
        { topic: "Force and Pressure", class: "Class 8", weightage: "High", examPattern: "Numerical", subtopics: ["Contact/Non-contact Forces", "Pressure"] },
        { topic: "Friction", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Causes", "Increasing/Reducing", "Fluid Friction"] },
        { topic: "Sound", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Production", "Propagation", "Characteristics", "Noise"] },
        { topic: "Chemical Effects of Electric Current", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Conduction", "Electroplating"] },
        { topic: "Some Natural Phenomena", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Lightning", "Earthquakes"] },
        { topic: "Light", class: "Class 8", weightage: "High", examPattern: "MCQ", subtopics: ["Reflection", "Human Eye", "Care of Eyes"] },
        { topic: "Stars and the Solar System", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Moon", "Planets", "Constellations"] },
        { topic: "Pollution of Air and Water", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Causes", "Effects", "Prevention"] },

        // Class 7
        { topic: "Nutrition in Plants", class: "Class 7", weightage: "Medium", examPattern: "MCQ", subtopics: ["Autotrophic", "Heterotrophic", "Photosynthesis"] },
        { topic: "Nutrition in Animals", class: "Class 7", weightage: "Medium", examPattern: "MCQ", subtopics: ["Digestion in Humans", "Ruminants", "Amoeba"] },
        { topic: "Fibre to Fabric", class: "Class 7", weightage: "Low", examPattern: "MCQ", subtopics: ["Wool", "Silk", "Processing"] },
        { topic: "Heat", class: "Class 7", weightage: "Medium", examPattern: "MCQ", subtopics: ["Temperature", "Transfer of Heat"] },
        { topic: "Acids, Bases and Salts", class: "Class 7", weightage: "High", examPattern: "MCQ", subtopics: ["Indicators", "Neutralization"] },
        { topic: "Physical and Chemical Changes", class: "Class 7", weightage: "Medium", examPattern: "MCQ", subtopics: ["Rusting", "Crystallization"] },
        { topic: "Weather, Climate and Adaptations", class: "Class 7", weightage: "Medium", examPattern: "MCQ", subtopics: ["Climate Types", "Animal Adaptations"] },
        { topic: "Winds, Storms and Cyclones", class: "Class 7", weightage: "High", examPattern: "MCQ", subtopics: ["Air Pressure", "Thunderstorms", "Safety"] },
        { topic: "Soil", class: "Class 7", weightage: "Medium", examPattern: "MCQ", subtopics: ["Profile", "Types", "Crops"] },
        { topic: "Respiration in Organisms", class: "Class 7", weightage: "High", examPattern: "MCQ", subtopics: ["Breathing", "Cellular Respiration"] },
        { topic: "Transportation in Animals and Plants", class: "Class 7", weightage: "High", examPattern: "MCQ", subtopics: ["Circulatory System", "Excretion", "Transport in Plants"] },
        { topic: "Reproduction in Plants", class: "Class 7", weightage: "Medium", examPattern: "MCQ", subtopics: ["Asexual", "Sexual", "Seed Dispersal"] },
        { topic: "Motion and Time", class: "Class 7", weightage: "High", examPattern: "Numerical", subtopics: ["Speed", "Distance-Time Graphs"] },
        { topic: "Electric Current and its Effects", class: "Class 7", weightage: "High", examPattern: "MCQ", subtopics: ["Heating Effect", "Magnetic Effect", "Electromagnet"] },
        { topic: "Light", class: "Class 7", weightage: "High", examPattern: "MCQ", subtopics: ["Lenses", "Mirrors"] },
        { topic: "Water: A Precious Resource", class: "Class 7", weightage: "Medium", examPattern: "MCQ", subtopics: ["Availability", "Management"] },
        { topic: "Forests: Our Lifeline", class: "Class 7", weightage: "Medium", examPattern: "MCQ", subtopics: ["Ecosystem", "Conservation"] },
        { topic: "Wastewater Story", class: "Class 7", weightage: "Low", examPattern: "MCQ", subtopics: ["Sewage Treatment", "Sanitation"] },

        // Class 6
        { topic: "Food: Where Does it Come From?", class: "Class 6", weightage: "Medium", examPattern: "MCQ", subtopics: ["Ingredients", "Sources"] },
        { topic: "Components of Food", class: "Class 6", weightage: "High", examPattern: "MCQ", subtopics: ["Nutrients", "Balanced Diet", "Deficiency Diseases"] },
        { topic: "Fibre to Fabric", class: "Class 6", weightage: "Medium", examPattern: "MCQ", subtopics: ["Spinning", "Weaving", "Knitting"] },
        { topic: "Sorting Materials into Groups", class: "Class 6", weightage: "Medium", examPattern: "MCQ", subtopics: ["Properties of Materials"] },
        { topic: "Separation of Substances", class: "Class 6", weightage: "High", examPattern: "MCQ", subtopics: ["Methods of Separation"] },
        { topic: "Changes Around Us", class: "Class 6", weightage: "Medium", examPattern: "MCQ", subtopics: ["Reversible/Irreversible", "Expansion"] },
        { topic: "Getting to Know Plants", class: "Class 6", weightage: "High", examPattern: "MCQ", subtopics: ["Herbs", "Shrubs", "Trees", "Parts of Plant"] },
        { topic: "Body Movements", class: "Class 6", weightage: "High", examPattern: "MCQ", subtopics: ["Joints", "Muscles", "Gait of Animals"] },
        { topic: "The Living Organisms and Their Surroundings", class: "Class 6", weightage: "Medium", examPattern: "MCQ", subtopics: ["Habitats", "Adaptations", "Living Characteristics"] },
        { topic: "Motion and Measurement of Distances", class: "Class 6", weightage: "High", examPattern: "Numerical", subtopics: ["Units", "Types of Motion"] },
        { topic: "Light, Shadows and Reflections", class: "Class 6", weightage: "High", examPattern: "MCQ", subtopics: ["Luminous", "Shadows", "Pinhole Camera"] },
        { topic: "Electricity and Circuits", class: "Class 6", weightage: "High", examPattern: "MCQ", subtopics: ["Cell", "Bulb", "Switch", "Conductors"] },
        { topic: "Fun with Magnets", class: "Class 6", weightage: "Medium", examPattern: "MCQ", subtopics: ["Poles", "Attraction/Repulsion"] },
        { topic: "Water", class: "Class 6", weightage: "Medium", examPattern: "MCQ", subtopics: ["Uses", "Water Cycle", "Conservation"] },
        { topic: "Air Around Us", class: "Class 6", weightage: "Medium", examPattern: "MCQ", subtopics: ["Composition", "Oxygen", "Uses"] },
        { topic: "Garbage In, Garbage Out", class: "Class 6", weightage: "Low", examPattern: "MCQ", subtopics: ["Waste Management", "Recycling", "Vermicomposting"] }
    ],
    "Social Science": [
        // Class 10
        { topic: "The Rise of Nationalism in Europe", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["French Revolution", "Unification"] },
        { topic: "Nationalism in India", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Non-Cooperation", "Civil Disobedience"] },
        { topic: "The Making of a Global World", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Pre-modern world", "19th Century"] },
        { topic: "The Age of Industrialisation", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Factories", "Industrial Growth"] },
        { topic: "Print Culture and the Modern World", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Print Revolution", "Reading Mania"] },
        { topic: "Resources and Development", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Land", "Soil Types"] },
        { topic: "Forest and Wildlife Resources", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Conservation", "Flora and Fauna"] },
        { topic: "Water Resources", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Scarcity", "Management"] },
        { topic: "Agriculture", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Crops", "Farming Types"] },
        { topic: "Minerals and Energy Resources", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Distribution", "Conservation"] },
        { topic: "Manufacturing Industries", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Importance", "Classification"] },
        { topic: "Lifelines of National Economy", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Transport", "Communication"] },
        { topic: "Power Sharing", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Forms", "Belgium/Sri Lanka"] },
        { topic: "Federalism", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Decentralization"] },
        { topic: "Gender, Religion and Caste", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Politics", "Social Division"] },
        { topic: "Political Parties", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Functions", "Challenges"] },
        { topic: "Outcomes of Democracy", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Accountability", "Economic Growth"] },
        { topic: "Development", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Income", "Public Facilities"] },
        { topic: "Sectors of the Indian Economy", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Primary/Secondary/Tertiary"] },
        { topic: "Money and Credit", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Banks", "SHGs"] },
        { topic: "Globalisation and the Indian Economy", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["MNCs", "Trade"] },
        { topic: "Consumer Rights", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Exploitation", "Awareness"] },

        // Class 9
        { topic: "The French Revolution", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Causes", "Events", "Impact"] },
        { topic: "Socialism in Europe and the Russian Revolution", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Social changes", "Bolsheviks"] },
        { topic: "Nazism and the Rise of Hitler", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Ideology", "Impact", "Holocaust"] },
        { topic: "Forest Society and Colonialism", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Deforestation", "Commercial Forestry"] },
        { topic: "Pastoralists in the Modern World", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Nomadism", "Colonial Rule"] },
        { topic: "India - Size and Location", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Coordinates", "Neighbors"] },
        { topic: "Physical Features of India", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Himalayas", "Plains", "Plateau"] },
        { topic: "Drainage", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["River Systems", "Lakes"] },
        { topic: "Climate", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Monsoon", "Seasons"] },
        { topic: "Natural Vegetation and Wildlife", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Forests", "Conservation"] },
        { topic: "Population", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Growth", "Distribution"] },
        { topic: "What is Democracy? Why Democracy?", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Features", "Arguments"] },
        { topic: "Constitutional Design", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Making of Constitution", "Values"] },
        { topic: "Electoral Politics", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Elections", "Code of Conduct"] },
        { topic: "Working of Institutions", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Parliament", "Executive", "Judiciary"] },
        { topic: "Democratic Rights", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Fundamental Rights"] },
        { topic: "The Story of Village Palampur", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Farming", "Non-farm activities"] },
        { topic: "People as Resource", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Health", "Education", "Unemployment"] },
        { topic: "Poverty as a Challenge", class: "Class 9", weightage: "High", examPattern: "Passage", subtopics: ["Poverty Line", "Estimates"] },
        { topic: "Food Security in India", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["PDS", "Buffer Stock"] },

        // Class 8
        { topic: "How, When and Where", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Dates", "Periodisation"] },
        { topic: "From Trade to Territory", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["East India Company", "Battle of Plassey"] },
        { topic: "Ruling the Countryside", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Permanent Settlement", "Ryotwari"] },
        { topic: "Tribals, Dikus and the Vision of a Golden Age", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Tribal Lives", "Birsa Munda"] },
        { topic: "When People Rebel", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["1857 Revolt", "Aftermath"] },
        { topic: "Civilising the \"Native\", Educating the Nation", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["English Education", "Orientalists"] },
        { topic: "Women, Caste and Reform", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Reform Movements", "Sati", "Widow Remarriage"] },
        { topic: "The Making of the National Movement", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["1870s-1947", "Gandhian Era"] },
        { topic: "India After Independence", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Partition", "Constitution"] },
        { topic: "Resources", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Types", "Conservation"] },
        { topic: "Land, Soil, Water, Natural Vegetation", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Distribution", "Conservation"] },
        { topic: "Mineral and Power Resources", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Extraction", "Distribution"] },
        { topic: "Agriculture", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Farming Systems", "Crops"] },
        { topic: "Industries", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Iron and Steel", "Textile"] },
        { topic: "Human Resources", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Distribution", "Population"] },
        { topic: "The Indian Constitution", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Key Features", "Fundamental Rights"] },
        { topic: "Understanding Secularism", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Indian Secularism"] },
        { topic: "Why Do We Need a Parliament?", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Role", "Functions"] },
        { topic: "Understanding Laws", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Rule of Law", "Unpopular Laws"] },
        { topic: "Judiciary", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Structure", "Role"] },
        { topic: "Understanding Our Criminal Justice System", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Police", "Courts", "Fair Trial"] },
        { topic: "Understanding Marginalisation", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Adivasis", "Minorities"] },
        { topic: "Confronting Marginalisation", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Laws", "Rights"] },
        { topic: "Public Facilities", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Water", "Sanitation"] },
        { topic: "Law and Social Justice", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Worker Rights", "Bhopal Gas Tragedy"] },

        // Class 7
        { topic: "Tracing Changes Through a Thousand Years", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["New terms", "Historians"] },
        { topic: "New Kings and Kingdoms", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Cholas", "Administration"] },
        { topic: "The Delhi Sultans", class: "Class 7", weightage: "High", examPattern: "Passage", subtopics: ["Dynasties", "Administration", "Khaljis", "Tughlaqs"] },
        { topic: "The Mughal Empire", class: "Class 7", weightage: "High", examPattern: "Passage", subtopics: ["Akbar", "Humayun", "Aurangzeb", "Policies"] },
        { topic: "Rulers and Buildings", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Temples", "Mosques", "Tombs"] },
        { topic: "Towns, Traders and Craftspersons", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Hampi", "Surat", "Masulipatnam"] },
        { topic: "Tribes, Nomads and Settled Communities", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Gonds", "Ahoms"] },
        { topic: "Devotional Paths to the Divine", class: "Class 7", weightage: "High", examPattern: "Passage", subtopics: ["Bhakti Movement", "Sufism", "Nayanars", "Alvars"] },
        { topic: "The Making of Regional Cultures", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Kathak", "Miniature Painting", "Bengal"] },
        { topic: "Eighteenth-Century Political Formations", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Later Mughals", "Marathas", "Sikhs"] },
        { topic: "Environment", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Components", "Ecosystem"] },
        { topic: "Inside Our Earth", class: "Class 7", weightage: "High", examPattern: "Passage", subtopics: ["Crust", "Mantle", "Core", "Rocks"] },
        { topic: "Our Changing Earth", class: "Class 7", weightage: "High", examPattern: "Passage", subtopics: ["Volcanoes", "Earthquakes", "Wind", "Glaciers"] },
        { topic: "Air", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Atmosphere Composition", "Weather", "Climate"] },
        { topic: "Water", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Tides", "Currents", "Water Cycle"] },
        { topic: "Natural Vegetation and Wildlife", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Forests", "Grasslands"] },
        { topic: "Human Environment – Settlement, Transport", class: "Class 7", weightage: "Low", examPattern: "Passage", subtopics: ["Communication", "Transport types"] },
        { topic: "Human Environment Interactions", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Amazon Basin", "Ganga-Brahmaputra"] },
        { topic: "Life in the Temperate Grasslands", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Prairies", "Velds"] },
        { topic: "Life in the Deserts", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Sahara", "Ladakh"] },
        { topic: "On Equality", class: "Class 7", weightage: "High", examPattern: "Passage", subtopics: ["Dignity", "Democracy"] },
        { topic: "Role of the Government in Health", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Public vs Private", "Healthcare"] },
        { topic: "How the State Government Works", class: "Class 7", weightage: "High", examPattern: "Passage", subtopics: ["MLA", "Debates"] },
        { topic: "Growing up as Boys and Girls", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Gender Roles"] },
        { topic: "Women Change the World", class: "Class 7", weightage: "High", examPattern: "Passage", subtopics: ["Education", "Stereotypes"] },
        { topic: "Understanding Media", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Role", "Impact", "Advertising"] },
        { topic: "Markets Around Us", class: "Class 7", weightage: "Low", examPattern: "Passage", subtopics: ["Weekly Market", "Malls"] },
        { topic: "A Shirt in the Market", class: "Class 7", weightage: "Low", examPattern: "Passage", subtopics: ["Chain of Markets"] },
        { topic: "Struggles for Equality", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Tawa Matsya Sangh"] },

        // Class 6
        { topic: "What, Where, How and When?", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Sources", "Archaeology"] },
        { topic: "From Hunting-Gathering to Growing Food", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Early Humans", "Domestication"] },
        { topic: "In the Earliest Cities", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Harappa", "Mohenjodaro"] },
        { topic: "What Books and Burials Tell Us", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Vedas", "Megaliths"] },
        { topic: "Kingdoms, Kings and an Early Republic", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Janapadas", "Mahajanapadas", "Magadha", "Vajji"] },
        { topic: "New Questions and Ideas", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Buddhism", "Jainism", "Upanishads"] },
        { topic: "Ashoka, The Emperor Who Gave Up War", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Dhamma", "Mauryan Empire"] },
        { topic: "Vital Villages, Thriving Towns", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Iron Tools", "Agriculture"] },
        { topic: "Traders, Kings and Pilgrims", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Silk Route", "Bhakti"] },
        { topic: "New Empires and Kingdoms", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Guptas", "Harsha", "Pallavas", "Chalukyas"] },
        { topic: "Buildings, Paintings and Books", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Stupas", "Epics", "Science"] },
        { topic: "The Earth in the Solar System", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Planets", "Stars", "Constellations"] },
        { topic: "Globe: Latitudes and Longitudes", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Equator", "Zones", "Time"] },
        { topic: "Motions of the Earth", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Rotation", "Revolution", "Seasons"] },
        { topic: "Maps", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Types", "Symbols", "Scale"] },
        { topic: "Major Domains of the Earth", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Lithosphere", "Atmosphere", "Hydrosphere", "Biosphere"] },
        { topic: "Major Landforms of the Earth", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Mountains", "Plateaus", "Plains"] },
        { topic: "Our Country - India", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Location", "Neighbors", "Physical Divisions"] },
        { topic: "India: Climate, Vegetation and Wildlife", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Monsoon", "Forests"] },
        { topic: "Understanding Diversity", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Differences", "Unity in Diversity"] },
        { topic: "Diversity and Discrimination", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Prejudice", "Stereotypes", "Inequality"] },
        { topic: "What is Government?", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Types", "Democratic Government"] },
        { topic: "Key Elements of a Democratic Government", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Participation", "Conflict Resolution"] },
        { topic: "Panchayati Raj", class: "Class 6", weightage: "High", examPattern: "Passage", subtopics: ["Gram Sabha", "Gram Panchayat"] },
        { topic: "Rural Administration", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Patwari", "Police Station"] },
        { topic: "Urban Administration", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Municipal Corporation", "Ward Councillor"] },
        { topic: "Rural Livelihoods", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Farming", "Debt"] },
        { topic: "Urban Livelihoods", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Street Vendors", "Casual Workers"] }
    ],
    "English": [
        // Class 10 - First Flight & Footprints Without Feet
        { topic: "A Letter to God", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Lencho's Faith", "Irony"] },
        { topic: "Nelson Mandela: Long Walk to Freedom", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Apartheid", "Courage", "Freedom"] },
        { topic: "Two Stories about Flying", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["His First Flight", "Black Aeroplane"] },
        { topic: "From the Diary of Anne Frank", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Kitty", "Hiding", "School Days"] },
        { topic: "Glimpses of India", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["A Baker from Goa", "Coorg", "Tea from Assam"] },
        { topic: "Madam Rides the Bus", class: "Class 10", weightage: "High", examPattern: "Passage", subtopics: ["Valli's Experience", "Observation"] },
        { topic: "The Sermon at Benares", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Kisa Gotami", "Grief and Acceptance"] },
        { topic: "Dust of Snow", class: "Class 10", weightage: "Low", examPattern: "Passage", subtopics: ["Nature's Healing", "Poem Analysis"] },
        { topic: "Fire and Ice", class: "Class 10", weightage: "Low", examPattern: "Passage", subtopics: ["Desire and Hatred", "Poem Analysis"] },
        { topic: "Amanda!", class: "Class 10", weightage: "Medium", examPattern: "Passage", subtopics: ["Freedom vs Restraint", "Parenting"] },
        { topic: "Tenses", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Usage", "Error Spotting"] },
        { topic: "Modals", class: "Class 10", weightage: "Medium", examPattern: "MCQ", subtopics: ["Usage", "Capability", "Permission"] },
        { topic: "Active and Passive Voice", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Conversion", "Tense Rules"] },
        { topic: "Reported Speech", class: "Class 10", weightage: "High", examPattern: "MCQ", subtopics: ["Direct to Indirect", "Imperatives"] },

        // Class 9 - Beehive & Moments
        { topic: "The Fun They Had", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Future Schools", "Telebooks"] },
        { topic: "The Sound of Music", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Evelyn Glennie", "Bismillah Khan"] },
        { topic: "The Little Girl", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Kezia's Bond", "Strict Father"] },
        { topic: "A Truly Beautiful Mind", class: "Class 9", weightage: "Medium", examPattern: "Passage", subtopics: ["Albert Einstein", "Genius"] },
        { topic: "The Road Not Taken", class: "Class 9", weightage: "Low", examPattern: "Passage", subtopics: ["Choices", "Regret", "Poem Analysis"] },
        { topic: "Wind", class: "Class 9", weightage: "Low", examPattern: "Passage", subtopics: ["Challenges", "Metaphor", "Poem Analysis"] },
        { topic: "Determiners", class: "Class 9", weightage: "Medium", examPattern: "MCQ", subtopics: ["Usage", "Articles", "Quantifiers"] },
        { topic: "Prepositions", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Time", "Place", "Motion"] },
        { topic: "Subject-Verb Concord", class: "Class 9", weightage: "High", examPattern: "MCQ", subtopics: ["Agreement Rules"] },

        // Class 8 - Honeydew & It So Happened
        { topic: "The Best Christmas Present in the World", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["War and Peace", "Jim and Connie"] },
        { topic: "The Tsunami", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Survival Stories", "Natural Disaster"] },
        { topic: "Glimpses of the Past", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Indian History", "Revolt of 1857"] },
        { topic: "Bepin Choudhury's Lapse of Memory", class: "Class 8", weightage: "High", examPattern: "Passage", subtopics: ["Psychological Trick", "Friendship"] },
        { topic: "The Summit Within", class: "Class 8", weightage: "Medium", examPattern: "Passage", subtopics: ["Mount Everest", "Mental Conquest"] },
        { topic: "The Ant and the Cricket", class: "Class 8", weightage: "Low", examPattern: "Passage", subtopics: ["Fable Analysis", "Hard Work"] },
        { topic: "Geography Lesson", class: "Class 8", weightage: "Low", examPattern: "Passage", subtopics: ["Perspective from Above", "Poem Analysis"] },
        { topic: "Nouns and Pronouns", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Types", "Usage"] },
        { topic: "Adjectives", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Degrees of Comparison", "Order"] },
        { topic: "Conjunctions", class: "Class 8", weightage: "Medium", examPattern: "MCQ", subtopics: ["Coordinating", "Subordinating"] },

        // Class 7 - Honeycomb & An Alien Hand
        { topic: "Three Questions", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["King's Quest", "Hermit's Wisdom"] },
        { topic: "A Gift of Chappals", class: "Class 7", weightage: "Medium", examPattern: "Passage", subtopics: ["Kindness", "Street Cat"] },
        { topic: "Gopal and the Hilsa Fish", class: "Class 7", weightage: "Low", examPattern: "Passage", subtopics: ["Wit and Humour"] },
        { topic: "The Squirrel", class: "Class 7", weightage: "Low", examPattern: "Passage", subtopics: ["Poem Analysis", "Observation"] },
        { topic: "Active and Passive Voice (Intro)", class: "Class 7", weightage: "High", examPattern: "MCQ", subtopics: ["Simple Tenses"] },
        { topic: "Articles", class: "Class 7", weightage: "High", examPattern: "MCQ", subtopics: ["A, An, The usage"] },

        // Class 6 - Honeysuckle & A Pact with the Sun
        { topic: "Who Did Patrick's Homework?", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Fantasy Story", "Elf"] },
        { topic: "How the Dog Found Himself a New Master", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Evolution of Bonding"] },
        { topic: "Taro's Reward", class: "Class 6", weightage: "Medium", examPattern: "Passage", subtopics: ["Filial Devotion", "Magic Waterfall"] },
        { topic: "A House, A Home", class: "Class 6", weightage: "Low", examPattern: "Passage", subtopics: ["Poem Analysis", "Family Spirit"] },
        { topic: "Sentences", class: "Class 6", weightage: "High", examPattern: "MCQ", subtopics: ["Types", "Subject vs Predicate"] },
        { topic: "Antonyms and Synonyms", class: "Class 6", weightage: "Medium", examPattern: "MCQ", subtopics: ["Word Meanings"] }
    ]
};

export const EXAM_SUBJECT_MAPPING: Record<string, string[]> = {
    'jee-mains': ['Physics', 'Chemistry', 'Mathematics'],
    'jee-advanced': ['Physics', 'Chemistry', 'Mathematics'],
    'neet': ['Physics', 'Chemistry', 'Biology'],
    'bitsat': ['Physics', 'Chemistry', 'Mathematics', 'English Proficiency', 'Logical Reasoning'],
    'upsc': ['History', 'Geography', 'Polity', 'Economy', 'General Science', 'Current Affairs'],
    'clat': ['English Proficiency', 'Current Affairs', 'Legal Reasoning', 'Logical Reasoning', 'Quantitative Techniques'],
    'gate': ['Engineering Mathematics', 'Logical Reasoning', 'Computer Science'],
    'class-12': ['Physics', 'Chemistry', 'Mathematics', 'Biology', 'English', 'Computer Science'],
    'class-11': ['Physics', 'Chemistry', 'Mathematics', 'Biology', 'English', 'Computer Science'],
    'class-10': ['Mathematics', 'Science', 'Social Science', 'English'],
    'class-9': ['Mathematics', 'Science', 'Social Science', 'English'],
    'class-8': ['Mathematics', 'Science', 'Social Science', 'English'],
    'class-7': ['Mathematics', 'Science', 'Social Science', 'English'],
    'class-6': ['Mathematics', 'Science', 'Social Science', 'English'],
};
