
const YOUTUBE_API_KEY = 'AIzaSyAj0_vu8OxPWVHvAWSRVN90y9GIStvQASY';

const ytCache: Record<string, { data: any[], timestamp: number }> = {};
const CACHE_TTL = 30 * 60 * 1000; // 30 minutes cache for YouTube

export const youtubeService = {
    searchVideos: async (query: string, region: string = 'IN'): Promise<any[]> => {
        if (!query || !YOUTUBE_API_KEY) return [];

        const cacheKey = `${query}_${region}`;
        if (ytCache[cacheKey] && (Date.now() - ytCache[cacheKey].timestamp < CACHE_TTL)) {
            return ytCache[cacheKey].data;
        }

        try {
            // India-First: Append positive regional keywords if not present
            let optimizedQuery = query;
            const regionalKeywords = ['hindi', 'bollywood', 'punjabi', 'indian', 'song'];
            if (!regionalKeywords.some(k => query.toLowerCase().includes(k))) {
                optimizedQuery += ' official song';
            }

            // Negative keywords to keep it clean, specifically excluding shorts and other non-music formats
            const sanitizedQuery = `${optimizedQuery} -shorts -#shorts -reels -tiktok -clip -bgm -loop -1hour -1hr -instrumental -beat -beats -focus -relaxing -sleep -meditation -jukebox`;

            // 1. Initial Search (snippet only)
            // Added videoCategoryId=10 to prioritize music content
            const searchUrl = `https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&q=${encodeURIComponent(sanitizedQuery)}&type=video&videoCategoryId=10&regionCode=${region}&key=${YOUTUBE_API_KEY}`;
            const searchRes = await fetch(searchUrl);
            if (!searchRes.ok) {
                // Fallback: If category filter fails (rare, but possible with some keys), try without it
                const fallbackUrl = `https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&q=${encodeURIComponent(sanitizedQuery)}&type=video&regionCode=${region}&key=${YOUTUBE_API_KEY}`;
                const fallbackRes = await fetch(fallbackUrl);
                if (!fallbackRes.ok) return [];
                const fallbackData = await fallbackRes.json();
                return await processSearchData(fallbackData);
            }

            const searchData = await searchRes.json();
            const tracks = await processSearchData(searchData);
            ytCache[cacheKey] = { data: tracks, timestamp: Date.now() };
            return tracks;
        } catch (error) {
            console.error('YouTube Service Deep Check Failed:', error);
            return [];
        }
    }
};

async function processSearchData(searchData: any) {
    const videoIds = searchData.items.map((item: any) => item.id.videoId).join(',');
    if (!videoIds) return [];

    // 2. Batch Detail Fetch (contentDetails for duration, statistics for popularity)
    const detailUrl = `https://www.googleapis.com/youtube/v3/videos?part=contentDetails,snippet,statistics&id=${videoIds}&key=${YOUTUBE_API_KEY}`;
    const detailRes = await fetch(detailUrl);
    if (!detailRes.ok) return [];

    const detailData = await detailRes.json();

    const tracks = detailData.items
        .map((item: any) => {
            const channel = item.snippet.channelTitle.toLowerCase();

            // --- SOURCE TRUST CALCULATION ---
            let trustTier = 0.4; // Default to noise
            let trustMetadata = 'Untrusted Source';

            // Big Labels and High Trust Sources
            const isHighTrustChannel =
                channel.includes('t-series') ||
                channel.includes('tseries') ||
                channel.includes('zee music') ||
                channel.includes('sony music') ||
                channel.includes('yrf') ||
                channel.includes('saregama') ||
                channel.includes('tips official') ||
                channel.includes('speed records') ||
                channel.includes('vevo') ||
                channel.includes('topic') || // Auto-generated by YouTube
                channel.includes('official') ||
                channel.endsWith(' music') ||
                channel.endsWith(' records');

            if (isHighTrustChannel) {
                trustTier = 1.0;
                trustMetadata = 'Verified Official/Topic Channel';
            }

            // Parse ISO 8601 Duration (e.g. PT4M20S -> 260)
            const durationStr = item.contentDetails.duration;
            let durationSec = 0;
            const match = durationStr.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
            if (match) {
                durationSec = (parseInt(match[1] || '0') * 3600) +
                    (parseInt(match[2] || '0') * 60) +
                    parseInt(match[3] || '0');
            }

            return {
                id: `yt-${item.id}`,
                title: item.snippet.title,
                artist: item.snippet.channelTitle,
                artwork: item.snippet.thumbnails.maxres?.url || item.snippet.thumbnails.high.url,
                url: `https://www.youtube.com/watch?v=${item.id}`,
                source: 'youtube',
                platformId: item.id,
                duration: durationSec,
                popularityScore: Math.min(1.0, parseInt(item.statistics.viewCount || '0') / 10000000), // Scale to 10M views
                trustTier,
                trustMetadata,
                audioFeatures: {
                    tempo: 100, // Default mid-tempo
                    energy: 0.6,
                    danceability: 0.5,
                    valence: 0.5,
                    acousticness: 0.2,
                    instrumentalness: 0
                }
            };
        })
        .filter((track: any) => {
            // STRICT FILTERING: Big Sources Only & No Shorts
            // 1. Must be high trust (tier 1.0)
            const isTrustedSource = track.trustTier >= 0.8;
            // 2. No shorts: Duration must be >= 60 seconds
            const isNotShort = track.duration >= 60;
            // 3. Keep away shorts-related keywords
            const hasShortsKeyword = track.title.toLowerCase().includes('shorts') || track.title.toLowerCase().includes('#shorts');

            const hasNoArtwork = !track.artwork || track.artwork.trim() === '';

            return isTrustedSource && isNotShort && !hasShortsKeyword && !hasNoArtwork;
        })
        .slice(0, 12);

    return tracks;
}
