/**
 * Rebuilds the JULES_COVERED_TOPICS.md registry from the current blogs.
 * Run: npx tsx scripts/rebuild-docs.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BLOG_DIR = path.join(__dirname, '../src/content/blogs');
const DOC_FILE = path.join(__dirname, '../JULES_COVERED_TOPICS.md');

async function start() {
    const files = fs.readdirSync(BLOG_DIR).filter(f => f.endsWith('.md'));
    console.log(`📚 Rebuilding documentation for ${files.length} blogs...`);

    const sections: Record<string, string[]> = {};

    for (const file of files) {
        const filePath = path.join(BLOG_DIR, file);
        const content = fs.readFileSync(filePath, 'utf8');
        const slug = file.replace('.md', '');

        const titleMatch = content.match(/title:\s*"(.+?)"/);
        const categoryMatch = content.match(/category:\s*"(.+?)"/);

        const title = titleMatch ? titleMatch[1] : slug.replace(/-/g, ' ');
        const category = categoryMatch ? categoryMatch[1] : 'General';

        if (!sections[category]) sections[category] = [];
        sections[category].push(`- [${title}](https://examcompass.pages.dev/blog/${slug}) \`(${file})\``);
    }

    let markdown = `# 📚 Jules Covered Topics\n\nHere is a complete list of all blog topics Jules has successfully generated and published so far:\n\n`;

    const sortedCategories = Object.keys(sections).sort();
    for (const cat of sortedCategories) {
        markdown += `## 📖 ${cat}\n`;
        markdown += sections[cat].sort().join('\n') + '\n\n';
    }

    markdown += `---\n\n**Total Blogs Generated by Jules:** ${files.length}\n*(Latest Sync: ${new Date().toLocaleTimeString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} — Jules 3.0 SEO Engine Enabled)*\n`;

    fs.writeFileSync(DOC_FILE, markdown);
    console.log(`✅ Documentation rebuilt successfully at ${DOC_FILE}`);
}

start();
